// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

type PrismaEnv = Record<string, string | undefined>;

function readNonEmptyEnv(env: PrismaEnv, key: string): string | undefined {
  const value = env[key]?.trim();
  return value ? value : undefined;
}

export function resolvePrismaDatabaseUrl(env: PrismaEnv = process.env): string | undefined {
  return readNonEmptyEnv(env, "DIRECT_URL") ?? readNonEmptyEnv(env, "DATABASE_URL");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: resolvePrismaDatabaseUrl(),
    shadowDatabaseUrl: readNonEmptyEnv(process.env, "SHADOW_DATABASE_URL"),
  },
});
