import './lib/dotenv'

import { execFileSync } from 'node:child_process'
import { cpSync, existsSync, mkdtempSync, readFileSync, rmSync } from 'node:fs'
import { homedir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import type { SuiJsonRpcClient } from '@mysten/sui/jsonRpc'
import { Transaction } from '@mysten/sui/transactions'
import { normalizeSuiAddress } from '@mysten/sui/utils'
import type { Ed25519Keypair } from '@mysten/sui/keypairs/ed25519'
import { createSuiGrpcCompatClient } from '../packages/soulidity-sdk/src/sui-grpc-compat'

import { loadKeypairFromEnv } from './lib/keypair'
import {
  assertLegacyAdminCap,
  assertLegacyMarketConfig,
  assertObjectAddressOwner,
  assertObjectShared,
  assertSuccessfulEffects,
  assertUpgradeCap,
  atomicWriteJson,
  atomicWriteText,
  moveFields,
  SOULIDITY_MAINNET_CHAIN_IDENTIFIER,
  SOULIDITY_MAINNET_GENESIS_DIGEST,
  transactionDigest,
} from './lib/soulidity-mainnet-migration'

// ── Types ──────────────────────────────────────────────────

interface SoulidityDeployment {
  callablePackageId: string
  originalPackageId: string
  animacraftProvenancePackageId: string
  /** @deprecated Compatibility alias for the original package id. */
  packageId: string
  marketConfigId: string
  marketConfigV2PackageId?: string
  marketConfigV2Id?: string
  marketAdminCapV2Id?: string
  kioskRegistryId: string
  kindRegistryId?: string
  soulTransferPolicyId: string
  collectionTransferPolicyId: string
  paymentCoinType: string
  publishTxDigest?: string
  upgradeCapId?: string
  // Mainnet multisig handoff
  marketAdminCapId?: string
  kindAdminCapId?: string
  soulPolicyCapId?: string
  collectionPolicyCapId?: string
  soulDisplayId?: string
  collectionDisplayId?: string
  multisigOwner?: string
  capTransferTxDigest?: string
  partialDeploymentReason?: string
}

type SoulidityDeploymentManifest = Record<string, SoulidityDeployment>

interface PublishObjectChange {
  type?: string
  packageId?: string
  objectType?: string
  objectId?: string
}

interface PublishEvent {
  type?: string
  parsedJson?: Record<string, unknown>
}

interface PublishResult {
  digest?: string
  effects?: {
    transactionDigest?: string
    status?: { status?: string; error?: string }
  }
  objectChanges?: PublishObjectChange[]
  events?: PublishEvent[]
}

type FreshDeploymentReadClient = Pick<SuiJsonRpcClient, 'getObject'>

interface SubmittedTransactionVerificationError extends Error {
  doNotRetry: true
  submittedDigest: string | null
}

interface PublishedSection {
  chainId: string
  packageId: string
  version: number
  toolchainVersion: string
  upgradeCapId: string
}

// ── Constants ──────────────────────────────────────────────

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const moveRoot = join(repoRoot, 'move')
const sourcePackageDir = join(repoRoot, 'move', 'soulidity')
const sourcePublishedTomlPath = join(sourcePackageDir, 'Published.toml')
const manifestPath = join(repoRoot, 'packages', 'soulidity-sdk', 'src', 'deployment-manifest.json')
const deploymentHistoryPath = join(
  repoRoot,
  'packages',
  'soulidity-sdk',
  'src',
  'deployment-manifest-history.json',
)
const releaseAttemptPath = join(
  repoRoot,
  'packages',
  'soulidity-sdk',
  'src',
  'deployment-release-attempt.json',
)

const DEFAULT_PUBLISH_GAS_BUDGET = 1_500_000_000n
const DEFAULT_TRANSFER_GAS_BUDGET = 200_000_000n
const MIN_DEPLOYER_BALANCE_MIST = 1_500_000_000n // 1.5 SUI
const MAINNET_FRESH_PUBLISH_CONFIRMATION =
  'CREATE_NEW_SOULIDITY_MAINNET_PACKAGE_FAMILY'

const EXIT_PUBLISH_FAILED = 1
const EXIT_TRANSFER_FAILED = 2
const EXIT_PREFLIGHT_FAILED = 3

const PUBLISHED_TOML_HEADER = `# Generated by Move
# This file contains metadata about published versions of this package in different environments
# This file SHOULD be committed to source control
`

interface ReleaseAttempt {
  operation: 'fresh-publish' | 'cap-transfer'
  network: 'mainnet' | 'testnet'
  status: 'signing' | 'submitted' | 'verified'
  startedAt: string
  deployerAddr: string
  priorPackageId?: string
  packageId?: string
  targetOwner?: string
  digest?: string
  deployment?: SoulidityDeployment
}

// ── I/O helpers ────────────────────────────────────────────

function readJsonFile<T>(path: string): T {
  return JSON.parse(readFileSync(path, 'utf8')) as T
}

function writeJsonFile(path: string, value: unknown) {
  atomicWriteJson(path, value)
}

export function readReleaseAttempt(path = releaseAttemptPath): ReleaseAttempt | null {
  if (!existsSync(path)) {
    throw new Error(
      `Release-attempt journal is missing at ${path}; refusing any signed release operation.`,
    )
  }
  const parsed = readJsonFile<unknown>(path)
  if (parsed === null) return null
  if (!parsed || typeof parsed !== 'object') {
    throw new Error(`Release-attempt journal ${path} must contain null or an object.`)
  }
  const attempt = parsed as Partial<ReleaseAttempt>
  if (
    (attempt.operation !== 'fresh-publish' && attempt.operation !== 'cap-transfer')
    || (attempt.network !== 'mainnet' && attempt.network !== 'testnet')
    || !['signing', 'submitted', 'verified'].includes(attempt.status ?? '')
    || typeof attempt.startedAt !== 'string'
    || typeof attempt.deployerAddr !== 'string'
  ) {
    throw new Error(`Release-attempt journal ${path} is malformed; refusing to sign.`)
  }
  return attempt as ReleaseAttempt
}

export function assertNoPendingReleaseAttempt(path = releaseAttemptPath): void {
  const attempt = readReleaseAttempt(path)
  if (!attempt) return
  throw new Error(
    `A ${attempt.operation} release attempt is still ${attempt.status}`
      + `${attempt.digest ? ` at digest ${attempt.digest}` : ''}. `
      + 'DO NOT RETRY or clear the journal until the signer history and all affected '
      + 'on-chain objects have been reconciled.',
  )
}

function writeReleaseAttempt(attempt: ReleaseAttempt | null): void {
  atomicWriteJson(releaseAttemptPath, attempt)
}

function beginReleaseAttempt(
  attempt: Omit<ReleaseAttempt, 'status' | 'startedAt'>,
): ReleaseAttempt {
  assertNoPendingReleaseAttempt()
  const record: ReleaseAttempt = {
    ...attempt,
    status: 'signing',
    startedAt: new Date().toISOString(),
  }
  writeReleaseAttempt(record)
  return record
}

function updateReleaseAttempt(
  attempt: ReleaseAttempt,
  patch: Partial<ReleaseAttempt>,
): ReleaseAttempt {
  const current = readReleaseAttempt()
  if (!current || current.startedAt !== attempt.startedAt) {
    throw new Error(
      'Release-attempt journal changed during the chain operation; refusing to overwrite it.',
    )
  }
  const updated = { ...current, ...patch }
  writeReleaseAttempt(updated)
  return updated
}

function clearReleaseAttempt(attempt: ReleaseAttempt): void {
  const current = readReleaseAttempt()
  if (!current || current.startedAt !== attempt.startedAt) {
    throw new Error(
      'Release-attempt journal changed before completion; refusing to clear it.',
    )
  }
  writeReleaseAttempt(null)
}

function requireString(value: unknown, fieldName: string): string {
  if (typeof value === 'string' && value.trim().length > 0) {
    return value.trim()
  }

  throw new Error(`Missing ${fieldName} in publish result`)
}

function exitWithError(code: number, msg: string): never {
  console.error(msg)
  process.exit(code)
}

// ── sui CLI helpers ────────────────────────────────────────

function resolveSuiBin() {
  const candidates = [
    process.env.SUI_BIN,
    join(homedir(), '.local', 'bin', 'sui'),
    'sui',
  ].filter((value): value is string => Boolean(value))

  for (const candidate of candidates) {
    if (candidate === 'sui' || existsSync(candidate)) {
      return candidate
    }
  }

  return 'sui'
}

function runSuiJson(suiBin: string, args: string[]) {
  return execFileSync(suiBin, args, {
    cwd: repoRoot,
    encoding: 'utf8',
    stdio: ['inherit', 'pipe', 'inherit'],
  })
}

function getActiveSuiEnv(suiBin: string) {
  return execFileSync(suiBin, ['client', 'active-env'], {
    cwd: repoRoot,
    encoding: 'utf8',
    stdio: ['inherit', 'pipe', 'inherit'],
  }).trim().toLowerCase()
}

export function resolveSuiToolchainVersion(suiBin: string): string {
  const out = execFileSync(suiBin, ['--version'], { encoding: 'utf8' }).trim()
  const match = out.match(/sui\s+([\d.]+)/i)
  return match ? match[1] : 'unknown'
}

// ── Args ───────────────────────────────────────────────────

interface ParsedArgs {
  dryRun: boolean
  dryRunTransferOnly: boolean
  resumeCapTransferFromManifest: boolean
  useEnvKey: boolean
  mainnetE2e: boolean
  gasBudget: string | null
  paymentCoinType: string | null
  transferCapsTo: string | null
  privKeyEnv: string
  breakGlassAllowMainnetFreshPublish: boolean
  breakGlassConfirm: string | null
}

export function parseArgs(argv: string[]): ParsedArgs {
  const result: ParsedArgs = {
    dryRun: false,
    dryRunTransferOnly: false,
    resumeCapTransferFromManifest: false,
    useEnvKey: false,
    mainnetE2e: false,
    gasBudget: null,
    paymentCoinType: null,
    transferCapsTo: null,
    privKeyEnv: 'MAINNET_DEPLOYER_PRIV_KEY',
    breakGlassAllowMainnetFreshPublish: false,
    breakGlassConfirm: null,
  }

  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i]

    if (arg === '--dry-run') { result.dryRun = true; continue }
    if (arg === '--dry-run-transfer-only') { result.dryRunTransferOnly = true; continue }
    if (arg === '--resume-cap-transfer-from-manifest') { result.resumeCapTransferFromManifest = true; continue }
    if (arg === '--use-env-key') { result.useEnvKey = true; continue }
    if (arg === '--mainnet-e2e') { result.mainnetE2e = true; continue }
    if (arg === '--break-glass-allow-mainnet-fresh-publish') {
      result.breakGlassAllowMainnetFreshPublish = true
      continue
    }

    const valueFor = (flag: string): string | null | undefined => {
      if (arg === flag) {
        const v = argv[i + 1]
        if (!v || v.startsWith('--')) {
          throw new Error(`${flag} requires a value`)
        }
        i += 1
        return v
      }
      if (arg.startsWith(`${flag}=`)) {
        return arg.slice(flag.length + 1)
      }
      return undefined
    }

    let v: string | null | undefined
    if ((v = valueFor('--gas-budget')) !== undefined) { result.gasBudget = v; continue }
    if ((v = valueFor('--payment-coin-type')) !== undefined) { result.paymentCoinType = v; continue }
    if ((v = valueFor('--transfer-caps-to')) !== undefined) { result.transferCapsTo = v; continue }
    if ((v = valueFor('--mainnet-priv-key-env')) !== undefined) { result.privKeyEnv = v ?? result.privKeyEnv; continue }
    if ((v = valueFor('--break-glass-confirm')) !== undefined) { result.breakGlassConfirm = v; continue }
    throw new Error(`Unknown argument: ${arg}`)
  }

  return result
}

// ── Published.toml read/write (preserves other [published.<env>] sections) ──

export function readPublishedTomlSections(path: string): Record<string, string> {
  if (!existsSync(path)) return {}
  const content = readFileSync(path, 'utf8')
  const lines = content.split('\n')
  const sections: Record<string, string[]> = {}
  let current: string | null = null

  for (const line of lines) {
    const m = line.match(/^\[published\.([a-z0-9]+)\]\s*$/)
    if (m) {
      current = m[1]
      sections[current] = [line]
      continue
    }
    if (current) {
      sections[current].push(line)
    }
  }

  const result: Record<string, string> = {}
  for (const env of Object.keys(sections)) {
    while (sections[env].length > 1 && sections[env][sections[env].length - 1].trim() === '') {
      sections[env].pop()
    }
    result[env] = sections[env].join('\n')
  }
  return result
}

function formatPublishedSection(env: string, s: PublishedSection): string {
  return [
    `[published.${env}]`,
    `chain-id = "${s.chainId}"`,
    `published-at = "${s.packageId}"`,
    `original-id = "${s.packageId}"`,
    `version = ${s.version}`,
    `toolchain-version = "${s.toolchainVersion}"`,
    `build-config = { flavor = "sui", edition = "2024" }`,
    `upgrade-capability = "${s.upgradeCapId}"`,
  ].join('\n')
}

export function writePublishedTomlSection(path: string, env: string, section: PublishedSection) {
  const sections = readPublishedTomlSections(path)
  sections[env] = formatPublishedSection(env, section)
  const ordered = Object.keys(sections).sort().map((k) => sections[k])
  const content = `${PUBLISHED_TOML_HEADER}\n${ordered.join('\n\n')}\n`
  atomicWriteText(path, content)
}

function copyPublishedTomlSectionFromTemp(tempPath: string, sourcePath: string, env: string) {
  const tempSections = readPublishedTomlSections(tempPath)
  const tempSectionText = tempSections[env]
  if (!tempSectionText) {
    throw new Error(`Temp Published.toml has no [published.${env}] section`)
  }
  const sourceSections = readPublishedTomlSections(sourcePath)
  sourceSections[env] = tempSectionText
  const ordered = Object.keys(sourceSections).sort().map((k) => sourceSections[k])
  const content = `${PUBLISHED_TOML_HEADER}\n${ordered.join('\n\n')}\n`
  atomicWriteText(sourcePath, content)
}

export function hasExistingDeployment(
  deployment: Partial<SoulidityDeployment> | null | undefined,
): boolean {
  return Boolean(
    deployment?.originalPackageId?.trim()
      || deployment?.callablePackageId?.trim()
      || deployment?.packageId?.trim(),
  )
}

export function assertMainnetFreshPublishAllowed(
  network: string,
  args: Pick<
    ParsedArgs,
    'breakGlassAllowMainnetFreshPublish' | 'breakGlassConfirm'
  >,
  previousDeployment: Partial<SoulidityDeployment> | null | undefined,
): void {
  if (network !== 'mainnet' || !hasExistingDeployment(previousDeployment)) return
  if (!args.breakGlassAllowMainnetFreshPublish) {
    throw new Error(
      'Pre-flight: mainnet already has a Soulidity package family. Fresh publish is disabled; '
        + 'use npm run upgrade:soulidity-mainnet instead. The break-glass path is only for an '
        + 'intentional new package family.',
    )
  }
  if (args.breakGlassConfirm !== MAINNET_FRESH_PUBLISH_CONFIRMATION) {
    throw new Error(
      'Pre-flight: break-glass fresh publish requires '
        + `--break-glass-confirm=${MAINNET_FRESH_PUBLISH_CONFIRMATION}`,
    )
  }
}

export function assertLegacyCliPublishAllowed(
  network: string,
  dryRun: boolean,
): void {
  if (network !== 'testnet') {
    throw new Error(
      `Network ${network || '<empty>'} is not allowed in the legacy sui CLI flow; `
        + 'only the exact testnet environment is supported. Set '
        + 'NEXT_PUBLIC_SUI_NETWORK=mainnet and use the guarded SDK flow with '
        + '--mainnet-e2e or an explicit capability handoff.',
    )
  }
  // Never sign through an environment-name based CLI path: a local alias named
  // `testnet` can still be pointed at another RPC. Every real publish must use
  // the SDK flow, which proves the chain identifier and owns the durable
  // release-attempt journal. This path is retained only for non-mutating CLI
  // simulation compatibility.
  if (!dryRun) {
    throw new Error(
      'Signed publishing is disabled in the legacy sui CLI flow. Use the guarded '
        + 'SDK flow with NEXT_PUBLIC_SUI_NETWORK and --use-env-key.',
    )
  }
}

function normalizeNonZeroSuiId(value: string, fieldName: string): string {
  let normalized: string
  try {
    normalized = normalizeSuiAddress(value.trim())
  } catch {
    throw new Error(`${fieldName} must be a valid Sui package ID`)
  }
  if (normalized === normalizeSuiAddress('0x0')) {
    throw new Error(`${fieldName} must be a non-zero Sui package ID`)
  }
  return normalized
}

/**
 * A break-glass Mainnet fresh publish creates a new Seal namespace. Before any
 * RPC, private-key read, or signature, require the production route payload to
 * already preserve the package family that is about to become historical.
 * This prevents a successful publish followed by a production env sync from
 * silently making existing Souls undecryptable.
 */
export function assertHistoricalSealRoutePreserved(
  network: string,
  previousDeployment: Partial<SoulidityDeployment> | null | undefined,
  rawRoutes: string | undefined,
): void {
  if (network !== 'mainnet' || !hasExistingDeployment(previousDeployment)) return

  const previousOriginal = previousDeployment?.originalPackageId?.trim()
    || previousDeployment?.packageId?.trim()
  const previousCallable = previousDeployment?.callablePackageId?.trim()
    || previousDeployment?.packageId?.trim()
  if (!previousOriginal || !previousCallable) {
    throw new Error(
      'Pre-flight: the previous Mainnet deployment is missing its original/callable package IDs; '
        + 'cannot preserve its historical Seal route.',
    )
  }

  const expectedSealPackageId = normalizeNonZeroSuiId(
    previousOriginal,
    'previous Mainnet originalPackageId',
  )
  const expectedCallablePackageId = normalizeNonZeroSuiId(
    previousCallable,
    'previous Mainnet callablePackageId',
  )
  const configured = rawRoutes?.trim()
  if (!configured) {
    throw new Error(
      'Pre-flight: NEXT_PUBLIC_SOULIDITY_SEAL_PACKAGE_ROUTES is required for a Mainnet '
        + 'fresh-family publish and must include the previous original/callable package pair.',
    )
  }

  let routes: unknown
  try {
    routes = JSON.parse(configured)
  } catch {
    throw new Error(
      'Pre-flight: NEXT_PUBLIC_SOULIDITY_SEAL_PACKAGE_ROUTES must be valid JSON.',
    )
  }
  if (!Array.isArray(routes)) {
    throw new Error(
      'Pre-flight: NEXT_PUBLIC_SOULIDITY_SEAL_PACKAGE_ROUTES must be a JSON array.',
    )
  }

  let preserved = false
  const callableByNamespace = new Map<string, string>()
  for (const [index, route] of routes.entries()) {
    if (!route || typeof route !== 'object') {
      throw new Error(
        `Pre-flight: historical Seal route ${index} must be an object.`,
      )
    }
    const value = route as Record<string, unknown>
    if (typeof value.sealPackageId !== 'string') {
      throw new Error(
        `Pre-flight: historical Seal route ${index}.sealPackageId must be a Sui package ID.`,
      )
    }
    if (typeof value.callablePackageId !== 'string') {
      throw new Error(
        `Pre-flight: historical Seal route ${index}.callablePackageId must be a Sui package ID.`,
      )
    }
    const sealPackageId = normalizeNonZeroSuiId(
      value.sealPackageId,
      `historical Seal route ${index}.sealPackageId`,
    )
    const callablePackageId = normalizeNonZeroSuiId(
      value.callablePackageId,
      `historical Seal route ${index}.callablePackageId`,
    )
    const existingCallable = callableByNamespace.get(sealPackageId)
    if (existingCallable && existingCallable !== callablePackageId) {
      throw new Error(
        `Pre-flight: historical Seal route ${index} conflicts with callable ${existingCallable} `
          + `for namespace ${sealPackageId}.`,
      )
    }
    callableByNamespace.set(sealPackageId, callablePackageId)
    if (
      sealPackageId === expectedSealPackageId
      && callablePackageId === expectedCallablePackageId
    ) {
      preserved = true
    }
  }

  if (!preserved) {
    throw new Error(
      'Pre-flight: NEXT_PUBLIC_SOULIDITY_SEAL_PACKAGE_ROUTES does not preserve the previous '
        + `Mainnet family (${expectedSealPackageId} -> ${expectedCallablePackageId}).`,
    )
  }
}

function archiveDeploymentBeforeOverwrite(
  network: string,
  deployment: SoulidityDeployment,
): void {
  let history: Array<{
    archivedAt: string
    network: string
    reason: string
    deployment: SoulidityDeployment
  }> = []
  if (existsSync(deploymentHistoryPath)) {
    const parsed = readJsonFile<unknown>(deploymentHistoryPath)
    if (!Array.isArray(parsed)) {
      throw new Error(`${deploymentHistoryPath} must contain a JSON array`)
    }
    history = parsed as typeof history
  }
  history.push({
    archivedAt: new Date().toISOString(),
    network,
    reason: 'break-glass fresh publish before deployment-manifest overwrite',
    deployment,
  })
  atomicWriteJson(deploymentHistoryPath, history)
}

// ── Deployment extraction ──────────────────────────────────

export function extractDeploymentFromPublishResult(
  result: PublishResult,
  previousDeployment?: Partial<SoulidityDeployment>,
  paymentCoinTypeOverride?: string | null,
): SoulidityDeployment {
  const publishedPackage = result.objectChanges?.find((change) => change.type === 'published')
  const packageId = requireString(publishedPackage?.packageId, 'published packageId')

  const marketInitialized = result.events?.find((event) => event.type?.endsWith('::market::MarketInitialized'))
  const marketPayload = marketInitialized?.parsedJson ?? {}
  const marketConfigId = requireString(marketPayload.config_id, 'market config id')
  const kioskRegistryId = requireString(marketPayload.registry_id, 'kiosk registry id')
  const soulTransferPolicyId = requireString(marketPayload.soul_policy_id, 'soul transfer policy id')
  const collectionTransferPolicyId = requireString(marketPayload.collection_policy_id, 'collection transfer policy id')

  const kindRegistryCreated = result.events?.find((event) => event.type?.endsWith('::kind_registry::KindRegistryCreated'))
  const kindRegistryPayload = kindRegistryCreated?.parsedJson ?? {}
  const kindRegistryId = requireString(kindRegistryPayload.registry_id, 'kind registry id')
  const kindAdminCapIdFromEvent = requireString(kindRegistryPayload.admin_cap_id, 'kind admin cap id')

  const findByObjectType = (typeStr: string) =>
    result.objectChanges?.find((c) => c.objectType === typeStr)?.objectId

  const upgradeCapId = requireString(
    findByObjectType('0x2::package::UpgradeCap'),
    'upgrade capability id',
  )

  const marketAdminCapId = requireString(
    findByObjectType(`${packageId}::market::MarketAdminCap`),
    'market admin capability id',
  )
  const kindAdminCapId = requireString(
    findByObjectType(`${packageId}::kind_registry::KindAdminCap`) ?? kindAdminCapIdFromEvent,
    'kind admin capability id',
  )
  const soulPolicyCapId = requireString(
    findByObjectType(`0x2::transfer_policy::TransferPolicyCap<${packageId}::soul::Soul>`),
    'Soul transfer policy capability id',
  )
  const collectionPolicyCapId = requireString(
    findByObjectType(`0x2::transfer_policy::TransferPolicyCap<${packageId}::collection::SoulCollectionRight>`),
    'collection transfer policy capability id',
  )
  const soulDisplayId = requireString(
    findByObjectType(`0x2::display::Display<${packageId}::soul::Soul>`),
    'Soul display id',
  )
  const collectionDisplayId = requireString(
    findByObjectType(`0x2::display::Display<${packageId}::collection::SoulCollectionRight>`),
    'collection display id',
  )

  const paymentCoinType = previousDeployment?.paymentCoinType?.trim()
    || paymentCoinTypeOverride?.trim()
  if (!paymentCoinType) {
    throw new Error('Missing paymentCoinType; seed deployment-manifest.json first or pass --payment-coin-type once')
  }
  const publishTxDigest = result.digest?.trim() || result.effects?.transactionDigest?.trim()

  return {
    callablePackageId: packageId,
    originalPackageId: packageId,
    animacraftProvenancePackageId: packageId,
    packageId,
    marketConfigId,
    // MarketConfigV2 is already defined by a fresh v5 package even though its
    // shared object is created only after the v6 upgrade retires v1. Preserve
    // that TypeOrigin so post-upgrade object/event matching does not
    // incorrectly use the v6 callable package.
    marketConfigV2PackageId: packageId,
    kioskRegistryId,
    kindRegistryId,
    soulTransferPolicyId,
    collectionTransferPolicyId,
    paymentCoinType,
    publishTxDigest: requireString(publishTxDigest, 'publish transaction digest'),
    upgradeCapId,
    marketAdminCapId,
    kindAdminCapId,
    soulPolicyCapId,
    collectionPolicyCapId,
    soulDisplayId,
    collectionDisplayId,
  }
}

function requiredDeploymentId(
  deployment: SoulidityDeployment,
  field: keyof SoulidityDeployment,
): string {
  return requireString(deployment[field], `deployment.${field}`)
}

async function readDeploymentObjects(
  client: FreshDeploymentReadClient,
  entries: Array<[string, string]>,
): Promise<Record<string, Awaited<ReturnType<FreshDeploymentReadClient['getObject']>>>> {
  const responses = await Promise.all(entries.map(async ([label, id]) => [
    label,
    await client.getObject({
      id,
      options: { showContent: true, showOwner: true, showType: true },
    }),
  ] as const))
  return Object.fromEntries(responses)
}

/**
 * Prove that every object emitted by a fresh publish is visible on chain with
 * the expected immutable type/owner and that the newly-created market starts
 * paused. Callers must complete this readback before persisting any release
 * record or attempting a capability handoff.
 */
export async function verifyFreshDeploymentOnChain(params: {
  client: FreshDeploymentReadClient
  deployment: SoulidityDeployment
  deployerAddr: string
}): Promise<{ paused: true }> {
  const { client, deployment, deployerAddr } = params
  const packageId = requiredDeploymentId(deployment, 'originalPackageId')
  const ids = {
    marketConfig: requiredDeploymentId(deployment, 'marketConfigId'),
    marketAdminCap: requiredDeploymentId(deployment, 'marketAdminCapId'),
    upgradeCap: requiredDeploymentId(deployment, 'upgradeCapId'),
    kioskRegistry: requiredDeploymentId(deployment, 'kioskRegistryId'),
    kindRegistry: requiredDeploymentId(deployment, 'kindRegistryId'),
    kindAdminCap: requiredDeploymentId(deployment, 'kindAdminCapId'),
    soulTransferPolicy: requiredDeploymentId(deployment, 'soulTransferPolicyId'),
    collectionTransferPolicy: requiredDeploymentId(
      deployment,
      'collectionTransferPolicyId',
    ),
    soulPolicyCap: requiredDeploymentId(deployment, 'soulPolicyCapId'),
    collectionPolicyCap: requiredDeploymentId(deployment, 'collectionPolicyCapId'),
    soulDisplay: requiredDeploymentId(deployment, 'soulDisplayId'),
    collectionDisplay: requiredDeploymentId(deployment, 'collectionDisplayId'),
  }
  const objects = await readDeploymentObjects(client, Object.entries(ids))

  const market = assertLegacyMarketConfig(objects.marketConfig, packageId)
  if (!market.paused) {
    throw new Error('Fresh Soulidity MarketConfig is active; expected paused=true')
  }
  if (market.feeRecipient !== normalizeSuiAddress(deployerAddr)) {
    throw new Error(
      `Fresh Soulidity fee recipient is ${market.feeRecipient}; expected deployer ${normalizeSuiAddress(deployerAddr)}`,
    )
  }
  assertLegacyAdminCap(objects.marketAdminCap, packageId, deployerAddr)
  assertUpgradeCap(objects.upgradeCap, packageId, deployerAddr)

  const sharedObjects: Array<[string, string, string]> = [
    ['kioskRegistry', `${packageId}::market::KioskRegistry`, 'Soulidity KioskRegistry'],
    ['kindRegistry', `${packageId}::kind_registry::KindRegistry`, 'Soulidity KindRegistry'],
    [
      'soulTransferPolicy',
      `0x2::transfer_policy::TransferPolicy<${packageId}::soul::Soul>`,
      'Soul transfer policy',
    ],
    [
      'collectionTransferPolicy',
      `0x2::transfer_policy::TransferPolicy<${packageId}::collection::SoulCollectionRight>`,
      'collection transfer policy',
    ],
  ]
  for (const [key, type, label] of sharedObjects) {
    moveFields(objects[key], type, label)
    assertObjectShared(objects[key], label)
  }

  const addressOwnedObjects: Array<[string, string, string]> = [
    ['kindAdminCap', `${packageId}::kind_registry::KindAdminCap`, 'Soulidity KindAdminCap'],
    [
      'soulPolicyCap',
      `0x2::transfer_policy::TransferPolicyCap<${packageId}::soul::Soul>`,
      'Soul transfer policy capability',
    ],
    [
      'collectionPolicyCap',
      `0x2::transfer_policy::TransferPolicyCap<${packageId}::collection::SoulCollectionRight>`,
      'collection transfer policy capability',
    ],
    [
      'soulDisplay',
      `0x2::display::Display<${packageId}::soul::Soul>`,
      'Soul display',
    ],
    [
      'collectionDisplay',
      `0x2::display::Display<${packageId}::collection::SoulCollectionRight>`,
      'collection display',
    ],
  ]
  for (const [key, type, label] of addressOwnedObjects) {
    moveFields(objects[key], type, label)
    assertObjectAddressOwner(objects[key], deployerAddr, label)
  }

  return { paused: true }
}

/** Confirm that a governance handoff reached finality for every transferred object. */
export async function verifyCapTransferOwners(params: {
  client: FreshDeploymentReadClient
  deployment: SoulidityDeployment
  expectedOwner: string
}): Promise<void> {
  const { client, deployment, expectedOwner } = params
  const packageId = requiredDeploymentId(deployment, 'originalPackageId')
  const callablePackageId = requiredDeploymentId(deployment, 'callablePackageId')
  const ids = {
    marketAdminCap: requiredDeploymentId(deployment, 'marketAdminCapId'),
    kindAdminCap: requiredDeploymentId(deployment, 'kindAdminCapId'),
    upgradeCap: requiredDeploymentId(deployment, 'upgradeCapId'),
    soulPolicyCap: requiredDeploymentId(deployment, 'soulPolicyCapId'),
    collectionPolicyCap: requiredDeploymentId(deployment, 'collectionPolicyCapId'),
    soulDisplay: requiredDeploymentId(deployment, 'soulDisplayId'),
    collectionDisplay: requiredDeploymentId(deployment, 'collectionDisplayId'),
  }
  const objects = await readDeploymentObjects(client, Object.entries(ids))

  assertLegacyAdminCap(objects.marketAdminCap, packageId, expectedOwner)
  assertUpgradeCap(objects.upgradeCap, callablePackageId, expectedOwner)
  const addressOwnedObjects: Array<[string, string, string]> = [
    ['kindAdminCap', `${packageId}::kind_registry::KindAdminCap`, 'Soulidity KindAdminCap'],
    [
      'soulPolicyCap',
      `0x2::transfer_policy::TransferPolicyCap<${packageId}::soul::Soul>`,
      'Soul transfer policy capability',
    ],
    [
      'collectionPolicyCap',
      `0x2::transfer_policy::TransferPolicyCap<${packageId}::collection::SoulCollectionRight>`,
      'collection transfer policy capability',
    ],
    [
      'soulDisplay',
      `0x2::display::Display<${packageId}::soul::Soul>`,
      'Soul display',
    ],
    [
      'collectionDisplay',
      `0x2::display::Display<${packageId}::collection::SoulCollectionRight>`,
      'collection display',
    ],
  ]
  for (const [key, type, label] of addressOwnedObjects) {
    moveFields(objects[key], type, label)
    assertObjectAddressOwner(objects[key], expectedOwner, label)
  }
}

function submittedTransactionVerificationError(
  label: string,
  digest: string,
  cause: unknown,
): SubmittedTransactionVerificationError {
  const error = new Error(
    `${label} transaction ${digest} was submitted, but finality/readback verification failed: `
      + `${cause instanceof Error ? cause.message : String(cause)}. `
      + `DO NOT RETRY this transaction until digest ${digest} has been inspected on chain.`,
  ) as SubmittedTransactionVerificationError
  error.doNotRetry = true
  error.submittedDigest = digest
  return error
}

function ambiguousTransactionSubmissionError(
  label: string,
  cause: unknown,
): SubmittedTransactionVerificationError {
  const error = new Error(
    `${label} submission returned an error and may still have reached the network: `
      + `${cause instanceof Error ? cause.message : String(cause)}. `
      + 'DO NOT RETRY until the wallet and RPC transaction history have been inspected.',
  ) as SubmittedTransactionVerificationError
  error.doNotRetry = true
  error.submittedDigest = null
  return error
}

function isSubmittedTransactionVerificationError(
  error: unknown,
): error is SubmittedTransactionVerificationError {
  return error instanceof Error
    && (error as Partial<SubmittedTransactionVerificationError>).doNotRetry === true
}

// ── Cap transfer PTB ───────────────────────────────────────

export function buildCapTransferPtb(
  deployment: SoulidityDeployment,
  multisig: string,
  deployerAddr: string,
): Transaction {
  const required: Array<keyof SoulidityDeployment> = [
    'marketAdminCapId',
    'kindAdminCapId',
    'upgradeCapId',
    'soulPolicyCapId',
    'collectionPolicyCapId',
    'soulDisplayId',
    'collectionDisplayId',
  ]
  for (const field of required) {
    if (!deployment[field]) {
      throw new Error(`Cannot build cap transfer PTB: deployment.${field} is missing`)
    }
  }

  const tx = new Transaction()

  tx.transferObjects(
    [
      tx.object(deployment.marketAdminCapId!),
      tx.object(deployment.kindAdminCapId!),
      tx.object(deployment.soulPolicyCapId!),
      tx.object(deployment.collectionPolicyCapId!),
      tx.object(deployment.upgradeCapId!),
      tx.object(deployment.soulDisplayId!),
      tx.object(deployment.collectionDisplayId!),
    ],
    tx.pure.address(multisig),
  )

  tx.setSender(deployerAddr)
  return tx
}

/**
 * Walk the on-chain `linkage_table` of every immediate dep (and recursively of
 * each newly-discovered package) and return the full transitive closure as a
 * deduplicated list of normalized package addresses. Sui's publish verifier
 * requires every transitively-reachable package to be declared in the publish
 * PTB's dependency list, but `sui move build --dump-bytecode-as-base64` only
 * surfaces the immediate deps from Move.lock. We invoke `sui client object`
 * via the CLI because the JSON-RPC `getObject({ showContent: true })` response
 * omits `linkage_table` for packages (it ships disassembled bytecode instead).
 */
export function expandTransitiveDependencies(
  suiBin: string,
  network: 'mainnet' | 'testnet',
  immediateDeps: string[],
): string[] {
  const seen = new Set<string>()
  const queue: string[] = []
  const enqueue = (id: string) => {
    let normalized: string
    try {
      normalized = normalizeSuiAddress(id)
    } catch {
      return
    }
    if (!seen.has(normalized)) {
      seen.add(normalized)
      queue.push(normalized)
    }
  }
  for (const dep of immediateDeps) enqueue(dep)

  while (queue.length > 0) {
    const id = queue.shift()!
    let raw: string
    try {
      raw = execFileSync(
        suiBin,
        ['client', '--client.env', network, 'object', id, '--json'],
        { encoding: 'utf8', stdio: ['inherit', 'pipe', 'pipe'] },
      )
    } catch {
      continue
    }
    let parsed: unknown
    try {
      parsed = JSON.parse(raw)
    } catch {
      continue
    }
    const pkg = (parsed as { content?: { Package?: { linkage_table?: Record<string, unknown> } } })?.content?.Package
    const linkageTable = pkg?.linkage_table
    if (!linkageTable || typeof linkageTable !== 'object') continue
    for (const linkedKey of Object.keys(linkageTable)) {
      enqueue(linkedKey)
    }
  }

  return [...seen]
}

async function executeCapTransferPtb(
  client: SuiJsonRpcClient,
  keypair: Ed25519Keypair,
  deployerAddr: string,
  deployment: SoulidityDeployment,
  multisig: string,
  gasBudgetOverride: string | null,
  network: 'mainnet' | 'testnet',
) {
  const tx = buildCapTransferPtb(deployment, multisig, deployerAddr)
  tx.setGasBudget(gasBudgetOverride ? BigInt(gasBudgetOverride) : DEFAULT_TRANSFER_GAS_BUDGET)

  let attempt = beginReleaseAttempt({
    operation: 'cap-transfer',
    network,
    deployerAddr,
    packageId: deployment.callablePackageId,
    targetOwner: multisig,
  })
  let submitted
  try {
    submitted = await client.signAndExecuteTransaction({
      signer: keypair,
      transaction: tx,
      options: { showEffects: true },
    })
  } catch (error) {
    throw ambiguousTransactionSubmissionError('Capability transfer', error)
  }
  let digest: string
  try {
    digest = transactionDigest(submitted)
  } catch (error) {
    throw ambiguousTransactionSubmissionError('Capability transfer', error)
  }
  attempt = updateReleaseAttempt(attempt, { status: 'submitted', digest })
  try {
    const finalized = await client.waitForTransaction({
      digest,
      options: {
        showEffects: true,
        showEvents: true,
        showObjectChanges: true,
      },
    })
    assertSuccessfulEffects(finalized, 'Finalized Soulidity capability transfer')
    const finalizedDigest = transactionDigest(finalized)
    if (finalizedDigest !== digest) {
      throw new Error(
        `Finalized capability-transfer digest ${finalizedDigest} differs from submitted digest ${digest}`,
      )
    }
    await verifyCapTransferOwners({
      client,
      deployment,
      expectedOwner: multisig,
    })
    attempt = updateReleaseAttempt(attempt, { status: 'verified' })
    return { digest, finalized, attempt }
  } catch (error) {
    throw submittedTransactionVerificationError('Capability transfer', digest, error)
  }
}

// ── CLI flow (testnet, sui client publish subprocess) ──────

function runCliPublishFlow(args: ParsedArgs) {
  const suiBin = resolveSuiBin()
  const activeEnv = getActiveSuiEnv(suiBin)
  const configuredNetwork = process.env.NEXT_PUBLIC_SUI_NETWORK?.trim().toLowerCase() || activeEnv

  if (configuredNetwork !== activeEnv) {
    exitWithError(
      EXIT_PREFLIGHT_FAILED,
      `NEXT_PUBLIC_SUI_NETWORK=${configuredNetwork} does not match active sui env ${activeEnv}`,
    )
  }
  const network = configuredNetwork

  try {
    assertLegacyCliPublishAllowed(network, args.dryRun)
  } catch (error) {
    exitWithError(EXIT_PREFLIGHT_FAILED, `Pre-flight: ${(error as Error).message}`)
  }

  const manifest = readJsonFile<SoulidityDeploymentManifest>(manifestPath)
  const previousDeployment = manifest[network]
  try {
    assertMainnetFreshPublishAllowed(network, args, previousDeployment)
    assertHistoricalSealRoutePreserved(
      network,
      previousDeployment,
      process.env.NEXT_PUBLIC_SOULIDITY_SEAL_PACKAGE_ROUTES,
    )
  } catch (error) {
    exitWithError(EXIT_PREFLIGHT_FAILED, (error as Error).message)
  }
  if (network === 'mainnet'
    && hasExistingDeployment(previousDeployment)
    && !args.dryRun) {
    archiveDeploymentBeforeOverwrite(network, previousDeployment)
    console.warn(
      `BREAK_GLASS_MAINNET_FRESH_PUBLISH: preserved the prior deployment in ${deploymentHistoryPath}`,
    )
  }

  const tempPackageDir = mkdtempSync(join(moveRoot, '.soulidity-publish-'))
  try {
    cpSync(sourcePackageDir, tempPackageDir, { recursive: true })
    rmSync(join(tempPackageDir, 'Published.toml'), { force: true })

    const publishArgs = ['client', 'publish', tempPackageDir]
    if (args.gasBudget) {
      publishArgs.push('--gas-budget', args.gasBudget)
    }
    publishArgs.push('--json')
    if (args.dryRun) {
      publishArgs.push('--dry-run')
    }

    const raw = runSuiJson(suiBin, publishArgs)
    const result = JSON.parse(raw) as PublishResult
    const deployment = extractDeploymentFromPublishResult(result, previousDeployment, args.paymentCoinType)

    if (args.dryRun) {
      console.log(JSON.stringify({ network, dryRun: true, deployment }, null, 2))
      return
    }

    manifest[network] = deployment
    writeJsonFile(manifestPath, manifest)

    const tempPublishedTomlPath = join(tempPackageDir, 'Published.toml')
    if (!existsSync(tempPublishedTomlPath)) {
      throw new Error(`Publish succeeded but ${tempPublishedTomlPath} was not generated`)
    }
    copyPublishedTomlSectionFromTemp(tempPublishedTomlPath, sourcePublishedTomlPath, network)

    console.log(JSON.stringify({
      network,
      suiBin,
      ...deployment,
      manifestPath,
      publishedTomlPath: sourcePublishedTomlPath,
    }, null, 2))
  } finally {
    rmSync(tempPackageDir, { recursive: true, force: true })
  }
}

// ── Mainnet TS SDK flow ────────────────────────────────────

async function runMainnetTsSdkFlow(args: ParsedArgs, network: 'mainnet' | 'testnet') {
  // Pre-flight 1: validate intent and immutable source records before touching
  // private-key material.
  if (args.mainnetE2e && args.transferCapsTo) {
    exitWithError(
      EXIT_PREFLIGHT_FAILED,
      'Pre-flight: --mainnet-e2e and --transfer-caps-to are mutually exclusive. '
        + 'Use --mainnet-e2e for the publish-only e2e step, then resume with '
        + '--resume-cap-transfer-from-manifest --transfer-caps-to=<multisig> for the handoff.',
    )
  }
  if (network === 'mainnet' && !args.transferCapsTo && !args.mainnetE2e) {
    exitWithError(
      EXIT_PREFLIGHT_FAILED,
      'Pre-flight: --transfer-caps-to is required for mainnet publish '
        + '(or pass --mainnet-e2e to publish without cap handoff and resume the transfer later)',
    )
  }
  if (args.transferCapsTo) {
    try {
      args.transferCapsTo = normalizeSuiAddress(args.transferCapsTo)
    } catch (e) {
      exitWithError(EXIT_PREFLIGHT_FAILED, `Pre-flight: invalid --transfer-caps-to: ${(e as Error).message}`)
    }
  }

  const manifest = readJsonFile<SoulidityDeploymentManifest>(manifestPath)
  const previousDeployment = manifest[network]
  try {
    assertMainnetFreshPublishAllowed(network, args, previousDeployment)
    assertHistoricalSealRoutePreserved(
      network,
      previousDeployment,
      process.env.NEXT_PUBLIC_SOULIDITY_SEAL_PACKAGE_ROUTES,
    )
  } catch (error) {
    exitWithError(EXIT_PREFLIGHT_FAILED, (error as Error).message)
  }
  if (!args.paymentCoinType && !previousDeployment?.paymentCoinType) {
    exitWithError(EXIT_PREFLIGHT_FAILED, `Pre-flight: --payment-coin-type required (or seed manifest.${network}.paymentCoinType first)`)
  }
  if (!args.dryRun) {
    try {
      assertNoPendingReleaseAttempt()
    } catch (error) {
      exitWithError(EXIT_PREFLIGHT_FAILED, `Pre-flight: ${(error as Error).message}`)
    }
  }

  // Pre-flight 2: bind the RPC to the requested chain, even though the SDK URL
  // is network-specific. This is a final defense against endpoint drift.
  const client = createSuiGrpcCompatClient(network)
  const chainIdentifier = (await client.getChainIdentifier()).trim()
  if (
    network === 'mainnet'
    && chainIdentifier.toLowerCase() !== SOULIDITY_MAINNET_CHAIN_IDENTIFIER
    && chainIdentifier !== SOULIDITY_MAINNET_GENESIS_DIGEST
  ) {
    exitWithError(
      EXIT_PREFLIGHT_FAILED,
      `Pre-flight: RPC chain ${chainIdentifier} is not Sui mainnet`,
    )
  }

  // Pre-flight 3: signer and balance. Dry-runs need a real sender/gas coin but
  // never call a signing API.
  let keypair: Ed25519Keypair
  try {
    keypair = loadKeypairFromEnv(args.privKeyEnv)
  } catch (e) {
    exitWithError(EXIT_PREFLIGHT_FAILED, `Pre-flight: ${(e as Error).message}`)
  }
  const deployerAddr = keypair.toSuiAddress()
  const balance = await client.getBalance({ owner: deployerAddr })
  const totalBalance = BigInt(balance.totalBalance)
  if (totalBalance < MIN_DEPLOYER_BALANCE_MIST) {
    exitWithError(
      EXIT_PREFLIGHT_FAILED,
      `Pre-flight: deployer ${deployerAddr} has ${totalBalance} MIST (< ${MIN_DEPLOYER_BALANCE_MIST} required = 1.5 SUI)`,
    )
  }

  // Build
  const suiBin = resolveSuiBin()
  const tempPackageDir = mkdtempSync(join(moveRoot, '.soulidity-publish-'))
  try {
    cpSync(sourcePackageDir, tempPackageDir, { recursive: true })
    rmSync(join(tempPackageDir, 'Published.toml'), { force: true })

    // Force the build to resolve deps against the target network so vendored
    // and Published.toml-declared addresses (e.g. mainnet vs testnet kiosk
    // extensions, Walrus mainnet-contracts vs testnet-contracts) pick the
    // right [published.<env>] section. Without this the build would fall back
    // to the operator's `sui client active-env`, which is often testnet even
    // when we're publishing to mainnet.
    const buildOut = execFileSync(suiBin, [
      'move',
      '--client.env', network,
      'build',
      '--dump-bytecode-as-base64',
      '--path', tempPackageDir,
    ], { encoding: 'utf8' })
    const built = JSON.parse(buildOut) as { modules: string[]; dependencies: string[] }

    // Sui CLI 1.70 build only reports the immediate deps declared in Move.toml /
    // Move.lock; it does NOT include transitive packages reachable via each dep's
    // on-chain linkage_table. Sui chain's publish verifier rejects the PTB with
    // `PublishUpgradeMissingDependency` if any transitively-reachable package is
    // missing from the dep list (e.g. USDC → stablecoin → two_step_role on
    // mainnet). Walk the linkage tables and union them in.
    const fullDependencies = expandTransitiveDependencies(suiBin, network, built.dependencies)

    // Publish PTB
    const gasBudget = args.gasBudget ? BigInt(args.gasBudget) : DEFAULT_PUBLISH_GAS_BUDGET
    const publishTx = new Transaction()
    const upgradeCap = publishTx.publish({ modules: built.modules, dependencies: fullDependencies })
    publishTx.transferObjects([upgradeCap], publishTx.pure.address(deployerAddr))
    publishTx.setSender(deployerAddr)
    publishTx.setGasBudget(gasBudget)

    // devInspect doesn't support `publish`; every mainnet/testnet SDK publish
    // path therefore simulates the exact transaction before any signature.
    const txBytes = await publishTx.build({ client })
    const dryRun = await client.dryRunTransactionBlock({ transactionBlock: txBytes })
    if (dryRun.effects?.status?.status !== 'success') {
      exitWithError(
        EXIT_PREFLIGHT_FAILED,
        `Pre-flight: publish dry-run failed: ${JSON.stringify(dryRun.effects?.status)}`,
      )
    }
    if (args.dryRun) {
      console.log(JSON.stringify({
        network,
        dryRun: true,
        status: dryRun.effects?.status,
        gasUsed: dryRun.effects?.gasUsed,
        objectChanges: dryRun.objectChanges?.length ?? 0,
        events: dryRun.events?.length ?? 0,
      }, null, 2))
      return
    }

    let publishAttempt = beginReleaseAttempt({
      operation: 'fresh-publish',
      network,
      deployerAddr,
      priorPackageId: previousDeployment?.callablePackageId
        ?? previousDeployment?.packageId,
    })
    let publishRes
    try {
      publishRes = await client.signAndExecuteTransaction({
        signer: keypair,
        transaction: publishTx,
        options: { showEffects: true, showEvents: true, showObjectChanges: true },
      })
    } catch (e) {
      exitWithError(
        EXIT_PUBLISH_FAILED,
        `Publish submission returned an error and may still have reached the network: `
          + `${(e as Error).message}. DO NOT RETRY until the wallet and RPC transaction history `
          + `have been inspected.`,
      )
    }

    let publishDigest: string
    try {
      publishDigest = transactionDigest(publishRes)
    } catch (error) {
      exitWithError(
        EXIT_PUBLISH_FAILED,
        `Publish returned without a transaction digest: ${(error as Error).message}. `
          + 'DO NOT RETRY until the wallet and RPC transaction history have been inspected.',
      )
    }
    publishAttempt = updateReleaseAttempt(publishAttempt, {
      status: 'submitted',
      digest: publishDigest,
    })

    let deployment: SoulidityDeployment
    try {
      const finalized = await client.waitForTransaction({
        digest: publishDigest,
        options: {
          showEffects: true,
          showEvents: true,
          showObjectChanges: true,
        },
      })
      assertSuccessfulEffects(finalized, 'Finalized Soulidity fresh publish')
      deployment = extractDeploymentFromPublishResult(
        finalized as PublishResult,
        previousDeployment,
        args.paymentCoinType,
      )
      if (deployment.publishTxDigest !== publishDigest) {
        throw new Error(
          `Finalized response digest ${deployment.publishTxDigest} differs from submitted digest ${publishDigest}`,
        )
      }
      await verifyFreshDeploymentOnChain({ client, deployment, deployerAddr })
      publishAttempt = updateReleaseAttempt(publishAttempt, {
        status: 'verified',
        packageId: deployment.packageId,
        deployment,
      })
    } catch (error) {
      exitWithError(
        EXIT_PUBLISH_FAILED,
        submittedTransactionVerificationError('Fresh publish', publishDigest, error).message,
      )
    }

    if (network === 'mainnet' && hasExistingDeployment(previousDeployment)) {
      archiveDeploymentBeforeOverwrite(network, previousDeployment)
      console.warn(
        `BREAK_GLASS_MAINNET_FRESH_PUBLISH: preserved the prior deployment in ${deploymentHistoryPath}`,
      )
    }

    // Persist publish results immediately
    manifest[network] = deployment
    writeJsonFile(manifestPath, manifest)

    // Write Published.toml [published.<network>] (preserves other env sections)
    writePublishedTomlSection(sourcePublishedTomlPath, network, {
      chainId: network === 'mainnet'
        ? SOULIDITY_MAINNET_CHAIN_IDENTIFIER
        : await client.getChainIdentifier(),
      packageId: deployment.packageId,
      version: 1,
      toolchainVersion: resolveSuiToolchainVersion(suiBin),
      upgradeCapId: deployment.upgradeCapId!,
    })
    clearReleaseAttempt(publishAttempt)

    // Cap transfer PTB
    if (args.transferCapsTo) {
      try {
        const transferRes = await executeCapTransferPtb(
          client,
          keypair,
          deployerAddr,
          deployment,
          args.transferCapsTo,
          args.gasBudget,
          network,
        )
        deployment.multisigOwner = args.transferCapsTo
        deployment.capTransferTxDigest = transferRes.digest
        manifest[network] = deployment
        writeJsonFile(manifestPath, manifest)
        clearReleaseAttempt(transferRes.attempt)
      } catch (e) {
        const reason = (e as Error).message
        deployment.partialDeploymentReason = reason
        manifest[network] = deployment
        writeJsonFile(manifestPath, manifest)
        console.error(`SOULIDITY_PARTIAL_DEPLOYMENT_NEEDS_RESUME=${deployment.packageId}`)
        console.error(`Cap transfer failed: ${reason}`)
        if (isSubmittedTransactionVerificationError(e)) {
          if (e.submittedDigest) {
            console.error(
              `Inspect submitted digest ${e.submittedDigest} on chain. Do not run the resume command yet.`,
            )
          } else {
            console.error(
              'Inspect the signer wallet and RPC transaction history. Do not run the resume command yet.',
            )
          }
        } else {
          console.error(`Resume with: npm run publish:soulidity -- --resume-cap-transfer-from-manifest --transfer-caps-to=${args.transferCapsTo}`)
        }
        process.exit(EXIT_TRANSFER_FAILED)
      }
    } else if (args.mainnetE2e) {
      console.warn(
        `SOULIDITY_MAINNET_E2E_PUBLISH_ONLY=${deployment.packageId}\n`
          + `Caps remain with deployer ${deployerAddr}. After smoke passes, run cap handoff:\n`
          + `  npm run publish:soulidity -- --resume-cap-transfer-from-manifest --transfer-caps-to=<multisig>`,
      )
    }

    console.log(JSON.stringify({
      network,
      suiBin,
      ...deployment,
      manifestPath,
      publishedTomlPath: sourcePublishedTomlPath,
    }, null, 2))
  } finally {
    rmSync(tempPackageDir, { recursive: true, force: true })
  }
}

// ── Resume cap transfer flow ───────────────────────────────

async function runResumeCapTransferFlow(args: ParsedArgs, network: 'mainnet' | 'testnet') {
  if (!args.dryRunTransferOnly) {
    try {
      assertNoPendingReleaseAttempt()
    } catch (error) {
      exitWithError(EXIT_PREFLIGHT_FAILED, `Pre-flight: ${(error as Error).message}`)
    }
  }
  // Pre-flight 1: priv key
  let keypair: Ed25519Keypair
  try {
    keypair = loadKeypairFromEnv(args.privKeyEnv)
  } catch (e) {
    exitWithError(EXIT_PREFLIGHT_FAILED, `Pre-flight: ${(e as Error).message}`)
  }
  const deployerAddr = keypair.toSuiAddress()

  if (!args.transferCapsTo) {
    exitWithError(EXIT_PREFLIGHT_FAILED, 'Pre-flight: --transfer-caps-to is required for resume mode')
  }
  try {
    args.transferCapsTo = normalizeSuiAddress(args.transferCapsTo)
  } catch (e) {
    exitWithError(EXIT_PREFLIGHT_FAILED, `Pre-flight: invalid --transfer-caps-to: ${(e as Error).message}`)
  }

  const manifest = readJsonFile<SoulidityDeploymentManifest>(manifestPath)
  const deployment = manifest[network]
  if (!deployment?.packageId) {
    exitWithError(EXIT_PREFLIGHT_FAILED, `Pre-flight: no manifest entry for ${network}; nothing to resume`)
  }
  if (deployment.capTransferTxDigest) {
    exitWithError(
      EXIT_PREFLIGHT_FAILED,
      `Pre-flight: capTransferTxDigest already set (${deployment.capTransferTxDigest}); nothing to resume`,
    )
  }
  for (const field of [
    'marketAdminCapId',
    'kindAdminCapId',
    'soulPolicyCapId',
    'collectionPolicyCapId',
    'upgradeCapId',
    'soulDisplayId',
    'collectionDisplayId',
  ] as const) {
    if (!deployment[field]) {
      exitWithError(EXIT_PREFLIGHT_FAILED, `Pre-flight: manifest.${network}.${field} missing; cannot resume`)
    }
  }

  const client = createSuiGrpcCompatClient(network)
  const balance = await client.getBalance({ owner: deployerAddr })
  if (BigInt(balance.totalBalance) < DEFAULT_TRANSFER_GAS_BUDGET) {
    exitWithError(
      EXIT_PREFLIGHT_FAILED,
      `Pre-flight: deployer ${deployerAddr} balance ${balance.totalBalance} MIST < ${DEFAULT_TRANSFER_GAS_BUDGET} required for transfer`,
    )
  }

  if (args.dryRunTransferOnly) {
    const tx = buildCapTransferPtb(deployment, args.transferCapsTo, deployerAddr)
    tx.setGasBudget(args.gasBudget ? BigInt(args.gasBudget) : DEFAULT_TRANSFER_GAS_BUDGET)
    const txBytes = await tx.build({ client })
    const dryRun = await client.dryRunTransactionBlock({ transactionBlock: txBytes })
    console.log(JSON.stringify({
      network,
      dryRunTransferOnly: true,
      status: dryRun.effects?.status,
      gasUsed: dryRun.effects?.gasUsed,
    }, null, 2))
    return
  }

  try {
    const transferRes = await executeCapTransferPtb(
      client,
      keypair,
      deployerAddr,
      deployment,
      args.transferCapsTo,
      args.gasBudget,
      network,
    )
    deployment.multisigOwner = args.transferCapsTo
    deployment.capTransferTxDigest = transferRes.digest
    delete deployment.partialDeploymentReason
    manifest[network] = deployment
    writeJsonFile(manifestPath, manifest)
    clearReleaseAttempt(transferRes.attempt)
    console.log(JSON.stringify({ network, resumed: true, ...deployment, manifestPath }, null, 2))
  } catch (e) {
    const reason = (e as Error).message
    console.error(`SOULIDITY_PARTIAL_DEPLOYMENT_NEEDS_RESUME=${deployment.packageId}`)
    console.error(`Resume cap transfer failed: ${reason}`)
    process.exit(EXIT_TRANSFER_FAILED)
  }
}

// ── Dispatch ───────────────────────────────────────────────

async function main() {
  const args = parseArgs(process.argv.slice(2))
  const network = process.env.NEXT_PUBLIC_SUI_NETWORK?.trim().toLowerCase()

  if (args.resumeCapTransferFromManifest) {
    if (!network) {
      exitWithError(EXIT_PREFLIGHT_FAILED, 'Pre-flight: NEXT_PUBLIC_SUI_NETWORK required for resume mode')
    }
    if (network !== 'mainnet' && network !== 'testnet') {
      exitWithError(EXIT_PREFLIGHT_FAILED, `Pre-flight: unsupported network for resume: ${network}`)
    }
    return runResumeCapTransferFlow(args, network)
  }

  if (network === 'mainnet' || args.useEnvKey) {
    const targetNetwork = network === 'mainnet' ? 'mainnet' : (network === 'testnet' ? 'testnet' : 'mainnet')
    return runMainnetTsSdkFlow(args, targetNetwork)
  }

  // Existing CLI mode for testnet (sui client publish subprocess + active-address)
  return runCliPublishFlow(args)
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((e) => {
    console.error(e)
    process.exit(EXIT_PUBLISH_FAILED)
  })
}
