import './lib/dotenv'

import { execFileSync } from 'node:child_process'
import { cpSync, existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { SuiJsonRpcClient, getJsonRpcFullnodeUrl } from '@mysten/sui/jsonRpc'
import { Transaction } from '@mysten/sui/transactions'
import { normalizeSuiAddress } from '@mysten/sui/utils'
import type { Ed25519Keypair } from '@mysten/sui/keypairs/ed25519'

import { loadKeypairFromEnv } from './lib/keypair'

// ── Types ──────────────────────────────────────────────────

interface SoulidityDeployment {
  packageId: string
  marketConfigId: string
  kioskRegistryId: string
  kindRegistryId?: string
  soulTransferPolicyId: string
  collectionTransferPolicyId: string
  paymentCoinType: string
  publishTxDigest?: string
  upgradeCapId?: string
  // Mainnet multisig handoff
  marketAdminCapId?: string
  kindAdminCapId?: string
  soulPolicyCapId?: string
  collectionPolicyCapId?: string
  soulDisplayId?: string
  collectionDisplayId?: string
  multisigOwner?: string
  capTransferTxDigest?: string
  partialDeploymentReason?: string
}

type SoulidityDeploymentManifest = Record<string, SoulidityDeployment>

interface PublishObjectChange {
  type?: string
  packageId?: string
  objectType?: string
  objectId?: string
}

interface PublishEvent {
  type?: string
  parsedJson?: Record<string, unknown>
}

interface PublishResult {
  digest?: string
  effects?: {
    transactionDigest?: string
    status?: { status?: string; error?: string }
  }
  objectChanges?: PublishObjectChange[]
  events?: PublishEvent[]
}

interface PublishedSection {
  chainId: string
  packageId: string
  version: number
  toolchainVersion: string
  upgradeCapId: string
}

// ── Constants ──────────────────────────────────────────────

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const moveRoot = join(repoRoot, 'move')
const sourcePackageDir = join(repoRoot, 'move', 'soulidity')
const sourcePublishedTomlPath = join(sourcePackageDir, 'Published.toml')
const manifestPath = join(repoRoot, 'web', 'lib', 'soulidity', 'deployment-manifest.json')

const DEFAULT_PUBLISH_GAS_BUDGET = 1_500_000_000n
const DEFAULT_TRANSFER_GAS_BUDGET = 200_000_000n
const MIN_DEPLOYER_BALANCE_MIST = 1_500_000_000n // 1.5 SUI

const EXIT_PUBLISH_FAILED = 1
const EXIT_TRANSFER_FAILED = 2
const EXIT_PREFLIGHT_FAILED = 3

const PUBLISHED_TOML_HEADER = `# Generated by Move
# This file contains metadata about published versions of this package in different environments
# This file SHOULD be committed to source control
`

// ── I/O helpers ────────────────────────────────────────────

function readJsonFile<T>(path: string): T {
  return JSON.parse(readFileSync(path, 'utf8')) as T
}

function writeJsonFile(path: string, value: unknown) {
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`, 'utf8')
}

function requireString(value: unknown, fieldName: string): string {
  if (typeof value === 'string' && value.trim().length > 0) {
    return value.trim()
  }

  throw new Error(`Missing ${fieldName} in publish result`)
}

function exitWithError(code: number, msg: string): never {
  console.error(msg)
  process.exit(code)
}

// ── sui CLI helpers ────────────────────────────────────────

function resolveSuiBin() {
  const candidates = [
    process.env.SUI_BIN,
    join(homedir(), '.local', 'bin', 'sui'),
    'sui',
  ].filter((value): value is string => Boolean(value))

  for (const candidate of candidates) {
    if (candidate === 'sui' || existsSync(candidate)) {
      return candidate
    }
  }

  return 'sui'
}

function runSuiJson(suiBin: string, args: string[]) {
  return execFileSync(suiBin, args, {
    cwd: repoRoot,
    encoding: 'utf8',
    stdio: ['inherit', 'pipe', 'inherit'],
  })
}

function getActiveSuiEnv(suiBin: string) {
  return execFileSync(suiBin, ['client', 'active-env'], {
    cwd: repoRoot,
    encoding: 'utf8',
    stdio: ['inherit', 'pipe', 'inherit'],
  }).trim().toLowerCase()
}

export function resolveSuiToolchainVersion(suiBin: string): string {
  const out = execFileSync(suiBin, ['--version'], { encoding: 'utf8' }).trim()
  const match = out.match(/sui\s+([\d.]+)/i)
  return match ? match[1] : 'unknown'
}

// ── Args ───────────────────────────────────────────────────

interface ParsedArgs {
  dryRun: boolean
  dryRunTransferOnly: boolean
  resumeCapTransferFromManifest: boolean
  useEnvKey: boolean
  mainnetE2e: boolean
  gasBudget: string | null
  paymentCoinType: string | null
  transferCapsTo: string | null
  privKeyEnv: string
}

export function parseArgs(argv: string[]): ParsedArgs {
  const result: ParsedArgs = {
    dryRun: false,
    dryRunTransferOnly: false,
    resumeCapTransferFromManifest: false,
    useEnvKey: false,
    mainnetE2e: false,
    gasBudget: null,
    paymentCoinType: null,
    transferCapsTo: null,
    privKeyEnv: 'MAINNET_DEPLOYER_PRIV_KEY',
  }

  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i]

    if (arg === '--dry-run') { result.dryRun = true; continue }
    if (arg === '--dry-run-transfer-only') { result.dryRunTransferOnly = true; continue }
    if (arg === '--resume-cap-transfer-from-manifest') { result.resumeCapTransferFromManifest = true; continue }
    if (arg === '--use-env-key') { result.useEnvKey = true; continue }
    if (arg === '--mainnet-e2e') { result.mainnetE2e = true; continue }

    const valueFor = (flag: string): string | null | undefined => {
      if (arg === flag) {
        const v = argv[i + 1] ?? null
        i += 1
        return v
      }
      if (arg.startsWith(`${flag}=`)) {
        return arg.slice(flag.length + 1)
      }
      return undefined
    }

    let v: string | null | undefined
    if ((v = valueFor('--gas-budget')) !== undefined) { result.gasBudget = v; continue }
    if ((v = valueFor('--payment-coin-type')) !== undefined) { result.paymentCoinType = v; continue }
    if ((v = valueFor('--transfer-caps-to')) !== undefined) { result.transferCapsTo = v; continue }
    if ((v = valueFor('--mainnet-priv-key-env')) !== undefined) { result.privKeyEnv = v ?? result.privKeyEnv; continue }
  }

  return result
}

// ── Published.toml read/write (preserves other [published.<env>] sections) ──

export function readPublishedTomlSections(path: string): Record<string, string> {
  if (!existsSync(path)) return {}
  const content = readFileSync(path, 'utf8')
  const lines = content.split('\n')
  const sections: Record<string, string[]> = {}
  let current: string | null = null

  for (const line of lines) {
    const m = line.match(/^\[published\.([a-z0-9]+)\]\s*$/)
    if (m) {
      current = m[1]
      sections[current] = [line]
      continue
    }
    if (current) {
      sections[current].push(line)
    }
  }

  const result: Record<string, string> = {}
  for (const env of Object.keys(sections)) {
    while (sections[env].length > 1 && sections[env][sections[env].length - 1].trim() === '') {
      sections[env].pop()
    }
    result[env] = sections[env].join('\n')
  }
  return result
}

function formatPublishedSection(env: string, s: PublishedSection): string {
  return [
    `[published.${env}]`,
    `chain-id = "${s.chainId}"`,
    `published-at = "${s.packageId}"`,
    `original-id = "${s.packageId}"`,
    `version = ${s.version}`,
    `toolchain-version = "${s.toolchainVersion}"`,
    `build-config = { flavor = "sui", edition = "2024" }`,
    `upgrade-capability = "${s.upgradeCapId}"`,
  ].join('\n')
}

export function writePublishedTomlSection(path: string, env: string, section: PublishedSection) {
  const sections = readPublishedTomlSections(path)
  sections[env] = formatPublishedSection(env, section)
  const ordered = Object.keys(sections).sort().map((k) => sections[k])
  const content = `${PUBLISHED_TOML_HEADER}\n${ordered.join('\n\n')}\n`
  writeFileSync(path, content, 'utf8')
}

function copyPublishedTomlSectionFromTemp(tempPath: string, sourcePath: string, env: string) {
  const tempSections = readPublishedTomlSections(tempPath)
  const tempSectionText = tempSections[env]
  if (!tempSectionText) {
    throw new Error(`Temp Published.toml has no [published.${env}] section`)
  }
  const sourceSections = readPublishedTomlSections(sourcePath)
  sourceSections[env] = tempSectionText
  const ordered = Object.keys(sourceSections).sort().map((k) => sourceSections[k])
  const content = `${PUBLISHED_TOML_HEADER}\n${ordered.join('\n\n')}\n`
  writeFileSync(sourcePath, content, 'utf8')
}

// ── Deployment extraction ──────────────────────────────────

export function extractDeploymentFromPublishResult(
  result: PublishResult,
  previousDeployment?: Partial<SoulidityDeployment>,
  paymentCoinTypeOverride?: string | null,
): SoulidityDeployment {
  const publishedPackage = result.objectChanges?.find((change) => change.type === 'published')
  const packageId = requireString(publishedPackage?.packageId, 'published packageId')

  const marketInitialized = result.events?.find((event) => event.type?.endsWith('::market::MarketInitialized'))
  const marketPayload = marketInitialized?.parsedJson ?? {}
  const marketConfigId = requireString(marketPayload.config_id, 'market config id')
  const kioskRegistryId = requireString(marketPayload.registry_id, 'kiosk registry id')
  const soulTransferPolicyId = requireString(marketPayload.soul_policy_id, 'soul transfer policy id')
  const collectionTransferPolicyId = requireString(marketPayload.collection_policy_id, 'collection transfer policy id')

  const kindRegistryCreated = result.events?.find((event) => event.type?.endsWith('::kind_registry::KindRegistryCreated'))
  const kindRegistryPayload = kindRegistryCreated?.parsedJson ?? {}
  const kindRegistryId = requireString(kindRegistryPayload.registry_id, 'kind registry id')
  const kindAdminCapIdFromEvent = requireString(kindRegistryPayload.admin_cap_id, 'kind admin cap id')

  const findByObjectType = (typeStr: string) =>
    result.objectChanges?.find((c) => c.objectType === typeStr)?.objectId

  const upgradeCapId = requireString(
    findByObjectType('0x2::package::UpgradeCap'),
    'upgrade capability id',
  )

  const marketAdminCapId = findByObjectType(`${packageId}::market::MarketAdminCap`)
  const kindAdminCapId = findByObjectType(`${packageId}::kind_registry::KindAdminCap`) ?? kindAdminCapIdFromEvent
  const soulPolicyCapId = findByObjectType(`0x2::transfer_policy::TransferPolicyCap<${packageId}::soul::Soul>`)
  const collectionPolicyCapId = findByObjectType(`0x2::transfer_policy::TransferPolicyCap<${packageId}::collection::SoulCollectionRight>`)
  const soulDisplayId = findByObjectType(`0x2::display::Display<${packageId}::soul::Soul>`)
  const collectionDisplayId = findByObjectType(`0x2::display::Display<${packageId}::collection::SoulCollectionRight>`)

  const paymentCoinType = previousDeployment?.paymentCoinType?.trim()
    || paymentCoinTypeOverride?.trim()
  if (!paymentCoinType) {
    throw new Error('Missing paymentCoinType; seed deployment-manifest.json first or pass --payment-coin-type once')
  }
  const publishTxDigest = result.digest?.trim() || result.effects?.transactionDigest?.trim()

  return {
    packageId,
    marketConfigId,
    kioskRegistryId,
    kindRegistryId,
    soulTransferPolicyId,
    collectionTransferPolicyId,
    paymentCoinType,
    publishTxDigest: requireString(publishTxDigest, 'publish transaction digest'),
    upgradeCapId,
    marketAdminCapId,
    kindAdminCapId,
    soulPolicyCapId,
    collectionPolicyCapId,
    soulDisplayId,
    collectionDisplayId,
  }
}

// ── Cap transfer PTB ───────────────────────────────────────

export function buildCapTransferPtb(
  deployment: SoulidityDeployment,
  multisig: string,
  deployerAddr: string,
): Transaction {
  const required: Array<keyof SoulidityDeployment> = [
    'marketAdminCapId',
    'kindAdminCapId',
    'upgradeCapId',
    'soulPolicyCapId',
    'collectionPolicyCapId',
    'soulDisplayId',
    'collectionDisplayId',
  ]
  for (const field of required) {
    if (!deployment[field]) {
      throw new Error(`Cannot build cap transfer PTB: deployment.${field} is missing`)
    }
  }

  const tx = new Transaction()

  tx.transferObjects(
    [
      tx.object(deployment.marketAdminCapId!),
      tx.object(deployment.kindAdminCapId!),
      tx.object(deployment.soulPolicyCapId!),
      tx.object(deployment.collectionPolicyCapId!),
      tx.object(deployment.upgradeCapId!),
      tx.object(deployment.soulDisplayId!),
      tx.object(deployment.collectionDisplayId!),
    ],
    tx.pure.address(multisig),
  )

  tx.setSender(deployerAddr)
  return tx
}

/**
 * Walk the on-chain `linkage_table` of every immediate dep (and recursively of
 * each newly-discovered package) and return the full transitive closure as a
 * deduplicated list of normalized package addresses. Sui's publish verifier
 * requires every transitively-reachable package to be declared in the publish
 * PTB's dependency list, but `sui move build --dump-bytecode-as-base64` only
 * surfaces the immediate deps from Move.lock. We invoke `sui client object`
 * via the CLI because the JSON-RPC `getObject({ showContent: true })` response
 * omits `linkage_table` for packages (it ships disassembled bytecode instead).
 */
export function expandTransitiveDependencies(
  suiBin: string,
  network: 'mainnet' | 'testnet',
  immediateDeps: string[],
): string[] {
  const seen = new Set<string>()
  const queue: string[] = []
  const enqueue = (id: string) => {
    let normalized: string
    try {
      normalized = normalizeSuiAddress(id)
    } catch {
      return
    }
    if (!seen.has(normalized)) {
      seen.add(normalized)
      queue.push(normalized)
    }
  }
  for (const dep of immediateDeps) enqueue(dep)

  while (queue.length > 0) {
    const id = queue.shift()!
    let raw: string
    try {
      raw = execFileSync(
        suiBin,
        ['client', '--client.env', network, 'object', id, '--json'],
        { encoding: 'utf8', stdio: ['inherit', 'pipe', 'pipe'] },
      )
    } catch {
      continue
    }
    let parsed: unknown
    try {
      parsed = JSON.parse(raw)
    } catch {
      continue
    }
    const pkg = (parsed as { content?: { Package?: { linkage_table?: Record<string, unknown> } } })?.content?.Package
    const linkageTable = pkg?.linkage_table
    if (!linkageTable || typeof linkageTable !== 'object') continue
    for (const linkedKey of Object.keys(linkageTable)) {
      enqueue(linkedKey)
    }
  }

  return [...seen]
}

async function executeCapTransferPtb(
  client: SuiJsonRpcClient,
  keypair: Ed25519Keypair,
  deployerAddr: string,
  deployment: SoulidityDeployment,
  multisig: string,
  gasBudgetOverride: string | null,
) {
  const tx = buildCapTransferPtb(deployment, multisig, deployerAddr)
  tx.setGasBudget(gasBudgetOverride ? BigInt(gasBudgetOverride) : DEFAULT_TRANSFER_GAS_BUDGET)

  const res = await client.signAndExecuteTransaction({
    signer: keypair,
    transaction: tx,
    options: { showEffects: true },
  })
  if (res.effects?.status?.status !== 'success') {
    throw new Error(`Transfer TX failed: ${JSON.stringify(res.effects?.status)}`)
  }
  return res
}

// ── CLI flow (testnet, sui client publish subprocess) ──────

function runCliPublishFlow(args: ParsedArgs) {
  const suiBin = resolveSuiBin()
  const activeEnv = getActiveSuiEnv(suiBin)
  const configuredNetwork = process.env.NEXT_PUBLIC_SUI_NETWORK?.trim().toLowerCase() || activeEnv

  if (configuredNetwork !== activeEnv) {
    exitWithError(
      EXIT_PREFLIGHT_FAILED,
      `NEXT_PUBLIC_SUI_NETWORK=${configuredNetwork} does not match active sui env ${activeEnv}`,
    )
  }
  const network = configuredNetwork

  const manifest = readJsonFile<SoulidityDeploymentManifest>(manifestPath)
  const previousDeployment = manifest[network]

  const tempPackageDir = mkdtempSync(join(moveRoot, '.soulidity-publish-'))
  try {
    cpSync(sourcePackageDir, tempPackageDir, { recursive: true })
    rmSync(join(tempPackageDir, 'Published.toml'), { force: true })

    const publishArgs = ['client', 'publish', tempPackageDir]
    if (args.gasBudget) {
      publishArgs.push('--gas-budget', args.gasBudget)
    }
    publishArgs.push('--json')
    if (args.dryRun) {
      publishArgs.push('--dry-run')
    }

    const raw = runSuiJson(suiBin, publishArgs)
    const result = JSON.parse(raw) as PublishResult
    const deployment = extractDeploymentFromPublishResult(result, previousDeployment, args.paymentCoinType)

    if (args.dryRun) {
      console.log(JSON.stringify({ network, dryRun: true, deployment }, null, 2))
      return
    }

    manifest[network] = deployment
    writeJsonFile(manifestPath, manifest)

    const tempPublishedTomlPath = join(tempPackageDir, 'Published.toml')
    if (!existsSync(tempPublishedTomlPath)) {
      throw new Error(`Publish succeeded but ${tempPublishedTomlPath} was not generated`)
    }
    copyPublishedTomlSectionFromTemp(tempPublishedTomlPath, sourcePublishedTomlPath, network)

    console.log(JSON.stringify({
      network,
      suiBin,
      ...deployment,
      manifestPath,
      publishedTomlPath: sourcePublishedTomlPath,
    }, null, 2))
  } finally {
    rmSync(tempPackageDir, { recursive: true, force: true })
  }
}

// ── Mainnet TS SDK flow ────────────────────────────────────

async function runMainnetTsSdkFlow(args: ParsedArgs, network: 'mainnet' | 'testnet') {
  // Pre-flight 1: priv key
  let keypair: Ed25519Keypair
  try {
    keypair = loadKeypairFromEnv(args.privKeyEnv)
  } catch (e) {
    exitWithError(EXIT_PREFLIGHT_FAILED, `Pre-flight: ${(e as Error).message}`)
  }
  const deployerAddr = keypair.toSuiAddress()

  // Pre-flight 2: required flags for mainnet
  if (args.mainnetE2e && args.transferCapsTo) {
    exitWithError(
      EXIT_PREFLIGHT_FAILED,
      'Pre-flight: --mainnet-e2e and --transfer-caps-to are mutually exclusive. '
        + 'Use --mainnet-e2e for the publish-only e2e step, then resume with '
        + '--resume-cap-transfer-from-manifest --transfer-caps-to=<multisig> for the handoff.',
    )
  }
  if (network === 'mainnet' && !args.transferCapsTo && !args.mainnetE2e) {
    exitWithError(
      EXIT_PREFLIGHT_FAILED,
      'Pre-flight: --transfer-caps-to is required for mainnet publish '
        + '(or pass --mainnet-e2e to publish without cap handoff and resume the transfer later)',
    )
  }
  if (args.transferCapsTo) {
    try {
      args.transferCapsTo = normalizeSuiAddress(args.transferCapsTo)
    } catch (e) {
      exitWithError(EXIT_PREFLIGHT_FAILED, `Pre-flight: invalid --transfer-caps-to: ${(e as Error).message}`)
    }
  }

  const manifest = readJsonFile<SoulidityDeploymentManifest>(manifestPath)
  const previousDeployment = manifest[network]
  if (!args.paymentCoinType && !previousDeployment?.paymentCoinType) {
    exitWithError(EXIT_PREFLIGHT_FAILED, `Pre-flight: --payment-coin-type required (or seed manifest.${network}.paymentCoinType first)`)
  }

  // Pre-flight 3: balance
  const client = new SuiJsonRpcClient({
    url: getJsonRpcFullnodeUrl(network),
    network,
  })
  const balance = await client.getBalance({ owner: deployerAddr })
  const totalBalance = BigInt(balance.totalBalance)
  if (totalBalance < MIN_DEPLOYER_BALANCE_MIST) {
    exitWithError(
      EXIT_PREFLIGHT_FAILED,
      `Pre-flight: deployer ${deployerAddr} has ${totalBalance} MIST (< ${MIN_DEPLOYER_BALANCE_MIST} required = 1.5 SUI)`,
    )
  }

  // Build
  const suiBin = resolveSuiBin()
  const tempPackageDir = mkdtempSync(join(moveRoot, '.soulidity-publish-'))
  try {
    cpSync(sourcePackageDir, tempPackageDir, { recursive: true })
    rmSync(join(tempPackageDir, 'Published.toml'), { force: true })

    // Force the build to resolve deps against the target network so vendored
    // and Published.toml-declared addresses (e.g. mainnet vs testnet kiosk
    // extensions, Walrus mainnet-contracts vs testnet-contracts) pick the
    // right [published.<env>] section. Without this the build would fall back
    // to the operator's `sui client active-env`, which is often testnet even
    // when we're publishing to mainnet.
    const buildOut = execFileSync(suiBin, [
      'move',
      '--client.env', network,
      'build',
      '--dump-bytecode-as-base64',
      '--path', tempPackageDir,
    ], { encoding: 'utf8' })
    const built = JSON.parse(buildOut) as { modules: string[]; dependencies: string[] }

    // Sui CLI 1.70 build only reports the immediate deps declared in Move.toml /
    // Move.lock; it does NOT include transitive packages reachable via each dep's
    // on-chain linkage_table. Sui chain's publish verifier rejects the PTB with
    // `PublishUpgradeMissingDependency` if any transitively-reachable package is
    // missing from the dep list (e.g. USDC → stablecoin → two_step_role on
    // mainnet). Walk the linkage tables and union them in.
    const fullDependencies = expandTransitiveDependencies(suiBin, network, built.dependencies)

    // Publish PTB
    const gasBudget = args.gasBudget ? BigInt(args.gasBudget) : DEFAULT_PUBLISH_GAS_BUDGET
    const publishTx = new Transaction()
    const upgradeCap = publishTx.publish({ modules: built.modules, dependencies: fullDependencies })
    publishTx.transferObjects([upgradeCap], publishTx.pure.address(deployerAddr))
    publishTx.setSender(deployerAddr)
    publishTx.setGasBudget(gasBudget)

    if (args.dryRun) {
      // devInspect doesn't support `publish`; use dryRunTransactionBlock,
      // which simulates a real signed TX (including publish dispatch and
      // verifier) without committing on-chain.
      const txBytes = await publishTx.build({ client })
      const dryRun = await client.dryRunTransactionBlock({ transactionBlock: txBytes })
      console.log(JSON.stringify({
        network,
        dryRun: true,
        status: dryRun.effects?.status,
        gasUsed: dryRun.effects?.gasUsed,
        objectChanges: dryRun.objectChanges?.length ?? 0,
        events: dryRun.events?.length ?? 0,
      }, null, 2))
      return
    }

    let publishRes
    try {
      publishRes = await client.signAndExecuteTransaction({
        signer: keypair,
        transaction: publishTx,
        options: { showEffects: true, showEvents: true, showObjectChanges: true },
      })
    } catch (e) {
      exitWithError(EXIT_PUBLISH_FAILED, `Publish failed: ${(e as Error).message}`)
    }

    if (publishRes.effects?.status?.status !== 'success') {
      exitWithError(
        EXIT_PUBLISH_FAILED,
        `Publish TX failed: ${JSON.stringify(publishRes.effects?.status)}`,
      )
    }

    const deployment = extractDeploymentFromPublishResult(
      publishRes as PublishResult,
      previousDeployment,
      args.paymentCoinType,
    )

    // Persist publish results immediately
    manifest[network] = deployment
    writeJsonFile(manifestPath, manifest)

    // Write Published.toml [published.<network>] (preserves other env sections)
    const chainId = await client.getChainIdentifier()
    writePublishedTomlSection(sourcePublishedTomlPath, network, {
      chainId,
      packageId: deployment.packageId,
      version: 1,
      toolchainVersion: resolveSuiToolchainVersion(suiBin),
      upgradeCapId: deployment.upgradeCapId!,
    })

    // Cap transfer PTB
    if (args.transferCapsTo) {
      try {
        const transferRes = await executeCapTransferPtb(
          client,
          keypair,
          deployerAddr,
          deployment,
          args.transferCapsTo,
          args.gasBudget,
        )
        deployment.multisigOwner = args.transferCapsTo
        deployment.capTransferTxDigest = transferRes.digest
        manifest[network] = deployment
        writeJsonFile(manifestPath, manifest)
      } catch (e) {
        const reason = (e as Error).message
        deployment.partialDeploymentReason = reason
        manifest[network] = deployment
        writeJsonFile(manifestPath, manifest)
        console.error(`SOULIDITY_PARTIAL_DEPLOYMENT_NEEDS_RESUME=${deployment.packageId}`)
        console.error(`Cap transfer failed: ${reason}`)
        console.error(`Resume with: npm run publish:soulidity -- --resume-cap-transfer-from-manifest --transfer-caps-to=${args.transferCapsTo}`)
        process.exit(EXIT_TRANSFER_FAILED)
      }
    } else if (args.mainnetE2e) {
      console.warn(
        `SOULIDITY_MAINNET_E2E_PUBLISH_ONLY=${deployment.packageId}\n`
          + `Caps remain with deployer ${deployerAddr}. After smoke passes, run cap handoff:\n`
          + `  npm run publish:soulidity -- --resume-cap-transfer-from-manifest --transfer-caps-to=<multisig>`,
      )
    }

    console.log(JSON.stringify({
      network,
      suiBin,
      ...deployment,
      manifestPath,
      publishedTomlPath: sourcePublishedTomlPath,
    }, null, 2))
  } finally {
    rmSync(tempPackageDir, { recursive: true, force: true })
  }
}

// ── Resume cap transfer flow ───────────────────────────────

async function runResumeCapTransferFlow(args: ParsedArgs, network: 'mainnet' | 'testnet') {
  // Pre-flight 1: priv key
  let keypair: Ed25519Keypair
  try {
    keypair = loadKeypairFromEnv(args.privKeyEnv)
  } catch (e) {
    exitWithError(EXIT_PREFLIGHT_FAILED, `Pre-flight: ${(e as Error).message}`)
  }
  const deployerAddr = keypair.toSuiAddress()

  if (!args.transferCapsTo) {
    exitWithError(EXIT_PREFLIGHT_FAILED, 'Pre-flight: --transfer-caps-to is required for resume mode')
  }
  try {
    args.transferCapsTo = normalizeSuiAddress(args.transferCapsTo)
  } catch (e) {
    exitWithError(EXIT_PREFLIGHT_FAILED, `Pre-flight: invalid --transfer-caps-to: ${(e as Error).message}`)
  }

  const manifest = readJsonFile<SoulidityDeploymentManifest>(manifestPath)
  const deployment = manifest[network]
  if (!deployment?.packageId) {
    exitWithError(EXIT_PREFLIGHT_FAILED, `Pre-flight: no manifest entry for ${network}; nothing to resume`)
  }
  if (deployment.capTransferTxDigest) {
    exitWithError(
      EXIT_PREFLIGHT_FAILED,
      `Pre-flight: capTransferTxDigest already set (${deployment.capTransferTxDigest}); nothing to resume`,
    )
  }
  for (const field of [
    'marketAdminCapId',
    'kindAdminCapId',
    'soulPolicyCapId',
    'collectionPolicyCapId',
    'upgradeCapId',
    'soulDisplayId',
    'collectionDisplayId',
  ] as const) {
    if (!deployment[field]) {
      exitWithError(EXIT_PREFLIGHT_FAILED, `Pre-flight: manifest.${network}.${field} missing; cannot resume`)
    }
  }

  const client = new SuiJsonRpcClient({
    url: getJsonRpcFullnodeUrl(network),
    network,
  })
  const balance = await client.getBalance({ owner: deployerAddr })
  if (BigInt(balance.totalBalance) < DEFAULT_TRANSFER_GAS_BUDGET) {
    exitWithError(
      EXIT_PREFLIGHT_FAILED,
      `Pre-flight: deployer ${deployerAddr} balance ${balance.totalBalance} MIST < ${DEFAULT_TRANSFER_GAS_BUDGET} required for transfer`,
    )
  }

  if (args.dryRunTransferOnly) {
    const tx = buildCapTransferPtb(deployment, args.transferCapsTo, deployerAddr)
    tx.setGasBudget(args.gasBudget ? BigInt(args.gasBudget) : DEFAULT_TRANSFER_GAS_BUDGET)
    const txBytes = await tx.build({ client })
    const dryRun = await client.dryRunTransactionBlock({ transactionBlock: txBytes })
    console.log(JSON.stringify({
      network,
      dryRunTransferOnly: true,
      status: dryRun.effects?.status,
      gasUsed: dryRun.effects?.gasUsed,
    }, null, 2))
    return
  }

  try {
    const transferRes = await executeCapTransferPtb(
      client,
      keypair,
      deployerAddr,
      deployment,
      args.transferCapsTo,
      args.gasBudget,
    )
    deployment.multisigOwner = args.transferCapsTo
    deployment.capTransferTxDigest = transferRes.digest
    delete deployment.partialDeploymentReason
    manifest[network] = deployment
    writeJsonFile(manifestPath, manifest)
    console.log(JSON.stringify({ network, resumed: true, ...deployment, manifestPath }, null, 2))
  } catch (e) {
    const reason = (e as Error).message
    console.error(`SOULIDITY_PARTIAL_DEPLOYMENT_NEEDS_RESUME=${deployment.packageId}`)
    console.error(`Resume cap transfer failed: ${reason}`)
    process.exit(EXIT_TRANSFER_FAILED)
  }
}

// ── Dispatch ───────────────────────────────────────────────

async function main() {
  const args = parseArgs(process.argv.slice(2))
  const network = process.env.NEXT_PUBLIC_SUI_NETWORK?.trim().toLowerCase()

  if (args.resumeCapTransferFromManifest) {
    if (!network) {
      exitWithError(EXIT_PREFLIGHT_FAILED, 'Pre-flight: NEXT_PUBLIC_SUI_NETWORK required for resume mode')
    }
    if (network !== 'mainnet' && network !== 'testnet') {
      exitWithError(EXIT_PREFLIGHT_FAILED, `Pre-flight: unsupported network for resume: ${network}`)
    }
    return runResumeCapTransferFlow(args, network)
  }

  if (network === 'mainnet' || args.useEnvKey) {
    const targetNetwork = network === 'mainnet' ? 'mainnet' : (network === 'testnet' ? 'testnet' : 'mainnet')
    return runMainnetTsSdkFlow(args, targetNetwork)
  }

  // Existing CLI mode for testnet (sui client publish subprocess + active-address)
  return runCliPublishFlow(args)
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((e) => {
    console.error(e)
    process.exit(EXIT_PUBLISH_FAILED)
  })
}
