[package]
name = "soul_object"
edition = "2024.beta"

[dependencies]
usdc = { local = "../test_usdc" }
Walrus = { git = "https://github.com/MystenLabs/walrus.git", subdir = "testnet-contracts/walrus", rev = "65b7dde1482dc666f8414ea83e010cd4e9900024" }
Kiosk = { local = "../vendor/kiosk", override = true }

[addresses]
soul_object = "0x0e4e2c28774221df59ff7a2bc8918362e8c1a0452e1c1c87bea13de2611a6b14"
