[package]
name = "soul_object"
edition = "2024.beta"

[dependencies]
usdc = { local = "../test_usdc" }
Walrus = { git = "https://github.com/MystenLabs/walrus.git", subdir = "testnet-contracts/walrus", rev = "65b7dde1482dc666f8414ea83e010cd4e9900024" }
Kiosk = { local = "../vendor/kiosk", override = true }

[addresses]
soul_object = "0x8a14f3c1c35ab5294d50d956eaf5d42bb7e5d146d841b088b71031eee25cb894"
