import {
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import {
  afterEach,
  describe,
  expect,
  it,
} from 'vitest'

import {
  assertCanonicalMainnetDeployment,
  assertExecutionConfirmation,
  atomicPatchMainnetDeployment,
  readDeploymentSnapshot,
  SOULIDITY_MAINNET_CONFIRM_UPGRADE,
  SOULIDITY_MAINNET_LEGACY_ADMIN_CAP,
  SOULIDITY_MAINNET_LEGACY_CONFIG,
  SOULIDITY_MAINNET_ORIGINAL_PACKAGE,
  SOULIDITY_MAINNET_UPGRADE_CAP,
} from '../../scripts/lib/soulidity-mainnet-migration'
import { assertLegacyPauseAbort } from '../../scripts/preflight-animacraft-market-retirement'
import {
  buildLegacyRetirementTransaction,
  extractRetirementObjectIds,
  parseRetirementArgs,
} from '../../scripts/retire-soulidity-legacy-market'
import {
  buildUpgradeTransaction,
  parseUpgradeArgs,
  renderUpdatedPublishedToml,
  validateBuiltMovePackage,
} from '../../scripts/upgrade-soulidity-mainnet'

const CALLABLE = `0x${'9'.repeat(64)}`
const CONFIG_V2 = `0x${'a'.repeat(64)}`
const ADMIN_V2 = `0x${'b'.repeat(64)}`

describe('controlled Soulidity mainnet upgrade args', () => {
  it('defaults to dry-run without loading/signing intent', () => {
    expect(parseUpgradeArgs([])).toMatchObject({
      execute: false,
      confirm: null,
      writeManifest: false,
      recordAnimacraftProvenanceOrigin: false,
      privKeyEnv: 'MAINNET_DEPLOYER_PRIV_KEY',
    })
  })

  it('requires the exact execution confirmation and forbids dry-run writes', () => {
    expect(() => parseUpgradeArgs(['--execute'])).toThrow(
      SOULIDITY_MAINNET_CONFIRM_UPGRADE,
    )
    expect(() => parseUpgradeArgs([
      '--execute',
      '--confirm=not-enough',
    ])).toThrow(SOULIDITY_MAINNET_CONFIRM_UPGRADE)
    expect(() => parseUpgradeArgs(['--write-manifest'])).toThrow(
      /only allowed together with --execute/,
    )
    expect(() => parseUpgradeArgs([
      '--dry-run',
      '--execute',
      `--confirm=${SOULIDITY_MAINNET_CONFIRM_UPGRADE}`,
    ])).toThrow(/mutually exclusive/)
  })

  it('accepts the fully explicit execution gate', () => {
    expect(parseUpgradeArgs([
      '--execute',
      `--confirm=${SOULIDITY_MAINNET_CONFIRM_UPGRADE}`,
      '--write-manifest',
      '--record-animacraft-provenance-origin',
    ])).toMatchObject({
      execute: true,
      writeManifest: true,
      recordAnimacraftProvenanceOrigin: true,
    })
  })
})

describe('upgrade build and PTB validation', () => {
  const built = {
    modules: ['AAAA'],
    dependencies: [`0x${'2'.padStart(64, '0')}`],
    digest: Array.from({ length: 32 }, (_, index) => index),
  }

  it('requires a complete toolchain-emitted digest', () => {
    expect(validateBuiltMovePackage(built)).toMatchObject({
      modules: ['AAAA'],
      digest: built.digest,
    })
    expect(() => validateBuiltMovePackage({
      ...built,
      digest: [1, 2],
    })).toThrow(/32-byte upgrade digest/)
  })

  it('builds authorize -> Upgrade -> commit as one PTB', () => {
    const tx = buildUpgradeTransaction({
      currentPackageId: SOULIDITY_MAINNET_ORIGINAL_PACKAGE,
      upgradeCapId: SOULIDITY_MAINNET_UPGRADE_CAP,
      policy: 0,
      built,
    })
    const data = JSON.parse(JSON.stringify(tx.getData()))
    expect(data.commands).toHaveLength(3)
    expect(data.commands[0].MoveCall.function).toBe('authorize_upgrade')
    expect(data.commands[1].$kind).toBe('Upgrade')
    expect(data.commands[2].MoveCall.function).toBe('commit_upgrade')
  })

  it('updates only the mainnet callable package while preserving its original TypeOrigin', () => {
    const current = SOULIDITY_MAINNET_ORIGINAL_PACKAGE
    const testnetSection = [
      '[published.testnet]',
      'chain-id = "testnet-chain"',
      'published-at = "0xtestnet"',
      'original-id = "0xtestnet"',
      'version = 7',
    ].join('\n')
    const next = renderUpdatedPublishedToml({
      content: [
        '# Generated by Move',
        '',
        '[published.mainnet]',
        'chain-id = "35834a8a"',
        `published-at = "${current}"`,
        `original-id = "${current}"`,
        'version = 1',
        'toolchain-version = "1.74.1"',
        'build-config = { flavor = "sui", edition = "2024" }',
        `upgrade-capability = "${SOULIDITY_MAINNET_UPGRADE_CAP}"`,
        '',
        testnetSection,
        '',
      ].join('\n'),
      currentPackageId: current,
      callablePackageId: CALLABLE,
      originalPackageId: current,
      upgradeCapId: SOULIDITY_MAINNET_UPGRADE_CAP,
      version: 2n,
      toolchainVersion: '1.75.0',
    })
    expect(next).toContain(`published-at = "${CALLABLE}"`)
    expect(next).toContain(`original-id = "${current}"`)
    expect(next).toContain('version = 2')
    expect(next).not.toContain(`original-id = "${CALLABLE}"`)
    expect(next).toContain(testnetSection)
  })
})

describe('retirement controls', () => {
  it('defaults to a retirement dry-run and separately gates pause/retire execution', () => {
    expect(parseRetirementArgs([])).toMatchObject({
      execute: false,
      pauseOnly: false,
      writeManifest: false,
    })
    expect(() => parseRetirementArgs([
      '--pause-only',
      '--execute',
      '--confirm=RETIRE_SOULIDITY_LEGACY_MARKET_MAINNET',
    ])).toThrow(/PAUSE_SOULIDITY_LEGACY_MARKET_MAINNET/)
    expect(() => parseRetirementArgs([
      '--execute',
      '--confirm=RETIRE_SOULIDITY_LEGACY_MARKET_MAINNET',
      '--write-manifest',
    ])).not.toThrow()
    expect(() => parseRetirementArgs([
      '--dry-run',
      '--execute',
      '--confirm=RETIRE_SOULIDITY_LEGACY_MARKET_MAINNET',
    ])).toThrow(/mutually exclusive/)
  })

  it('reasserts pause and retires the cap in one PTB', () => {
    const tx = buildLegacyRetirementTransaction({
      callablePackageId: CALLABLE,
      legacyConfigId: SOULIDITY_MAINNET_LEGACY_CONFIG,
      legacyAdminCapId: SOULIDITY_MAINNET_LEGACY_ADMIN_CAP,
    })
    const data = JSON.parse(JSON.stringify(tx.getData()))
    expect(data.commands).toHaveLength(2)
    expect(data.commands[0].MoveCall.function).toBe('update_paused')
    expect(data.commands[1].MoveCall.function).toBe('retire_legacy_market')
    expect(JSON.stringify(data.commands)).toContain(CALLABLE.slice(2))
  })

  it('extracts exactly one successor config and admin cap by defining package', () => {
    expect(extractRetirementObjectIds({
      objectChanges: [
        {
          type: 'created',
          objectType: `${CALLABLE}::market::MarketConfigV2`,
          objectId: CONFIG_V2,
        },
        {
          type: 'created',
          objectType: `${CALLABLE}::market::MarketAdminCapV2`,
          objectId: ADMIN_V2,
        },
      ],
    }, CALLABLE)).toEqual({
      marketConfigV2Id: CONFIG_V2,
      marketAdminCapV2Id: ADMIN_V2,
    })
    expect(() => extractRetirementObjectIds({
      objectChanges: [],
    }, CALLABLE)).toThrow(/exactly one/)
  })
})

describe('postflight proof parsing', () => {
  it('accepts only an EMarketPaused MoveAbort', () => {
    expect(assertLegacyPauseAbort({
      effects: {
        status: {
          status: 'failure',
          error: 'MoveAbort in 0xabc::market::init_personal_kiosk, abort code: 11',
        },
      },
    })).toContain('abort code: 11')
    expect(() => assertLegacyPauseAbort({
      effects: { status: { status: 'success' } },
    })).toThrow(/unexpectedly succeeded/)
    expect(() => assertLegacyPauseAbort({
      effects: {
        status: {
          status: 'failure',
          error: 'MoveAbort in 0xabc::market, abort code: 12',
        },
      },
    })).toThrow(/EMarketPaused/)
  })
})

describe('canonical deployment and atomic manifest patching', () => {
  const temporaryDirectories: string[] = []

  afterEach(() => {
    for (const directory of temporaryDirectories.splice(0)) {
      rmSync(directory, { recursive: true, force: true })
    }
  })

  it('rejects a manifest that redirects any canonical governance object', () => {
    expect(() => assertCanonicalMainnetDeployment({
      originalPackageId: SOULIDITY_MAINNET_ORIGINAL_PACKAGE,
      callablePackageId: SOULIDITY_MAINNET_ORIGINAL_PACKAGE,
      packageId: SOULIDITY_MAINNET_ORIGINAL_PACKAGE,
      marketConfigId: SOULIDITY_MAINNET_LEGACY_CONFIG,
      marketAdminCapId: SOULIDITY_MAINNET_LEGACY_ADMIN_CAP,
      upgradeCapId: `0x${'f'.repeat(64)}`,
    })).toThrow(/non-canonical mainnet UpgradeCap/)
  })

  it('patches fields without replacing the record and rejects concurrent writes', () => {
    const directory = mkdtempSync(join(tmpdir(), 'soulidity-migration-test-'))
    temporaryDirectories.push(directory)
    const path = join(directory, 'manifest.json')
    const initial = {
      testnet: { packageId: '0xtestnet' },
      mainnet: {
        packageId: SOULIDITY_MAINNET_ORIGINAL_PACKAGE,
        originalPackageId: SOULIDITY_MAINNET_ORIGINAL_PACKAGE,
        callablePackageId: SOULIDITY_MAINNET_ORIGINAL_PACKAGE,
        keepMe: 'unchanged',
      },
    }
    writeFileSync(path, `${JSON.stringify(initial, null, 2)}\n`)
    const snapshot = readDeploymentSnapshot(path)
    atomicPatchMainnetDeployment(snapshot, {
      callablePackageId: CALLABLE,
      marketConfigV2Id: CONFIG_V2,
    })
    const after = JSON.parse(readFileSync(path, 'utf8'))
    expect(after.mainnet.keepMe).toBe('unchanged')
    expect(after.mainnet.callablePackageId).toBe(CALLABLE)
    expect(after.testnet.packageId).toBe('0xtestnet')

    expect(() => atomicPatchMainnetDeployment(snapshot, {
      marketAdminCapV2Id: ADMIN_V2,
    })).toThrow(/changed during the chain operation/)
  })

  it('never treats confirmation as optional', () => {
    expect(() => assertExecutionConfirmation(true, null, 'CONFIRM')).toThrow(
      /no transaction was signed/,
    )
    expect(() => assertExecutionConfirmation(false, null, 'CONFIRM')).not.toThrow()
  })
})
